#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO_DIR"

export PATH="$HOME/.local/share/mise/shims:$(go env GOBIN 2>/dev/null || echo "$HOME/go/bin"):$PATH"

COMMIT=$(git rev-parse HEAD)
SHORT=$(git rev-parse --short HEAD)
DIRTY=""
if ! git diff --quiet HEAD -- msg/; then
  DIRTY="-dirty"
fi

echo "==> Generating Python types from Go (commit ${SHORT}${DIRTY})..."
go run ./cmd/genpy > py/llm_bridge_types/_msg.tmp

# Prepend version header to generated file.
OUTFILE="py/llm_bridge_types/msg.py"
HEADER="# AUTO-GENERATED — DO NOT EDIT THIS FILE.
#
# Generated from github.com/kayushkin/llm-bridge/msg @ ${COMMIT}${DIRTY}
# Source of truth: Go types in msg/*.go
# To regenerate: ./generate-py.sh
#
# Any manual changes will be overwritten on the next generation run.
"

TMPFILE=$(mktemp)
echo "$HEADER" > "$TMPFILE"
cat "py/llm_bridge_types/_msg.tmp" >> "$TMPFILE"
mv "$TMPFILE" "$OUTFILE"
rm -f "py/llm_bridge_types/_msg.tmp"

echo "    wrote $OUTFILE ($(wc -l < "$OUTFILE") lines, commit ${SHORT}${DIRTY})"
