// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/llm-bridge/msg @ 59ca93bb0b354522de7852f547cd2456b97aa028-dirty
// Source of truth: Go types in msg/*.go
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: config.go

/**
 * GenerationConfig holds provider-agnostic generation parameters.
 */
export interface GenerationConfig {
  max_tokens?: number /* int */;
  temperature?: number /* float64 */;
  top_p?: number /* float64 */;
  top_k?: number /* int */;
  stop_sequences?: string[];
  stream?: boolean;
  response_format?: ResponseFormat;
}
/**
 * ResponseFormat specifies structured output requirements.
 */
export interface ResponseFormat {
  type: string;
  json_schema?: Record<string, unknown>;
  strict?: boolean;
}
/**
 * AnthropicConfig holds Anthropic-specific request parameters.
 */
export interface AnthropicConfig {
  thinking_budget?: number /* int */;
  thinking_display?: string;
  effort?: string;
  container_id?: string;
  service_tier?: string;
  inference_geo?: string;
  assistant_prefill?: ContentBlock[];
  metadata?: { [key: string]: string};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * OpenAIConfig holds OpenAI-specific request parameters.
 */
export interface OpenAIConfig {
  prediction?: string;
  logprobs?: boolean;
  top_logprobs?: number /* int */;
  n?: number /* int */;
  frequency_penalty?: number /* float64 */;
  presence_penalty?: number /* float64 */;
  seed?: number /* int */;
  stream_include_usage?: boolean;
  store?: boolean;
  previous_response_id?: string;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * GeminiConfig holds Gemini-specific request parameters.
 */
export interface GeminiConfig {
  safety_settings?: SafetySetting[];
  cached_content?: string;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * OpenRouterConfig holds OpenRouter-specific request parameters.
 */
export interface OpenRouterConfig {
  models?: string[];
  route?: string;
  provider_prefs?: OpenRouterProviderPrefs;
  plugins?: OpenRouterPlugin[];
  debug?: boolean;
  top_a?: number /* float64 */;
  min_p?: number /* float64 */;
  repetition_penalty?: number /* float64 */;
  prediction?: string;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * OpenRouterProviderPrefs controls model routing preferences.
 */
export interface OpenRouterProviderPrefs {
  order?: string[];
  allow_fallbacks?: boolean;
  require_parameters?: boolean;
}
/**
 * OpenRouterPlugin is an OpenRouter plugin configuration.
 */
export interface OpenRouterPlugin {
  id: string;
  enabled: boolean;
}

//////////
// source: content.go

/**
 * BlockType identifies the kind of content block.
 */
export type BlockType = string;
export const BlockText: BlockType = "text";
export const BlockImage: BlockType = "image";
export const BlockAudio: BlockType = "audio";
export const BlockVideo: BlockType = "video";
export const BlockDocument: BlockType = "document";
export const BlockToolUse: BlockType = "tool_use";
export const BlockToolResult: BlockType = "tool_result";
export const BlockThinking: BlockType = "thinking";
export const BlockRedactedThinking: BlockType = "redacted_thinking";
export const BlockCodeExec: BlockType = "code_exec";
export const BlockCodeExecResult: BlockType = "code_exec_result";
export const BlockServerToolResult: BlockType = "server_tool_result";
export const BlockRefusal: BlockType = "refusal";
/**
 * ContentBlock is a discriminated union of all possible content block types.
 * Exactly one of the typed fields will be non-nil, matching Type.
 */
export interface ContentBlock {
  type: BlockType;
  text_block?: TextBlock;
  image_block?: ImageBlock;
  audio_block?: AudioBlock;
  video_block?: VideoBlock;
  document_block?: DocumentBlock;
  tool_use_block?: ToolUseBlock;
  tool_result_block?: ToolResultBlock;
  thinking_block?: ThinkingBlock;
  redacted_thinking_block?: RedactedThinkingBlock;
  code_exec_block?: CodeExecBlock;
  code_exec_result_block?: CodeExecResultBlock;
  server_tool_result_block?: ServerToolResultBlock;
  refusal_block?: RefusalBlock;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * TextBlock represents plain text content.
 */
export interface TextBlock {
  text: string;
  citations?: Citation[];
  cache_control?: CacheControl;
}
/**
 * Citation references a source document by character position.
 */
export interface Citation {
  type: string;
  cited_text: string;
  document_index: number /* int */;
  start_char_index?: number /* int */;
  end_char_index?: number /* int */;
  start_page?: number /* int */;
  end_page?: number /* int */;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * CacheControl is Anthropic's per-block cache hint.
 */
export interface CacheControl {
  type: string; // "ephemeral"
  ttl?: string;
}
/**
 * MediaSourceKind identifies how media data is provided.
 */
export type MediaSourceKind = string;
export const MediaBase64: MediaSourceKind = "base64";
export const MediaURL: MediaSourceKind = "url";
export const MediaFileID: MediaSourceKind = "file_id";
/**
 * MediaSource unifies how media (images, audio, video, docs) are referenced.
 */
export interface MediaSource {
  kind: MediaSourceKind;
  media_type: string;
  data: string;
  detail?: string;
  format?: string;
  filename?: string;
}
/**
 * ImageBlock represents an image in any encoding.
 */
export interface ImageBlock {
  source: MediaSource;
  cache_control?: CacheControl;
}
/**
 * AudioBlock represents audio content.
 */
export interface AudioBlock {
  source: MediaSource;
  cache_control?: CacheControl;
}
/**
 * VideoBlock represents video content.
 */
export interface VideoBlock {
  source: MediaSource;
  cache_control?: CacheControl;
}
/**
 * DocumentBlock represents a document (PDF, plain text, etc.).
 */
export interface DocumentBlock {
  source: MediaSource;
  title?: string;
  citations_enabled?: boolean;
  cache_control?: CacheControl;
}
/**
 * ToolUseBlock represents the model requesting a tool call.
 */
export interface ToolUseBlock {
  id: string;
  original_id: string;
  name: string;
  input: Record<string, unknown>;
  cache_control?: CacheControl;
}
/**
 * ToolResultBlock represents the result of a tool call.
 */
export interface ToolResultBlock {
  tool_use_id: string;
  original_tool_use_id: string;
  content?: ContentBlock[];
  is_error?: boolean;
  source_role?: string;
  tool_name?: string;
}
/**
 * ThinkingBlock represents model reasoning/thinking traces.
 */
export interface ThinkingBlock {
  text: string;
  signature?: string;
  budget_tokens?: number /* int */;
}
/**
 * RedactedThinkingBlock represents thinking content redacted by the provider.
 */
export interface RedactedThinkingBlock {
  data: string;
}
/**
 * CodeExecBlock represents a code execution request.
 */
export interface CodeExecBlock {
  language: string;
  code: string;
}
/**
 * CodeExecResultBlock represents the output of code execution.
 */
export interface CodeExecResultBlock {
  outcome: string;
  output: string;
}
/**
 * ServerToolResultBlock represents results from provider-hosted tools.
 */
export interface ServerToolResultBlock {
  tool_type: string;
  content: Record<string, unknown>;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * RefusalBlock represents the model explicitly refusing a request.
 */
export interface RefusalBlock {
  text: string;
}

//////////
// source: event.go

/**
 * Event is the unified harness event type.
 * All harness-specific events are normalized into this structure.
 */
export interface Event {
  type: EventType;
  harness: Harness;
  /**
   * BridgeSessionID is bridge-server's stable session id — the routing and
   * storage key. Bridges stamp every event with the same id bridge-server
   * passed in at session start. Required.
   */
  bridge_session_id: string;
  /**
   * HarnessSessionID is the harness-internal id at the time of emission
   * (Codex thread_id, Claude session_id, ...). Rotates when the harness mints
   * a new internal id (resume, fork). Informational — bridge-server stores
   * the latest reported value on the session row but never routes on it.
   */
  harness_session_id?: string;
  completion_id?: string;
  /**
   * ClientRequestID is the caller-minted per-turn identifier forwarded from
   * SendMessageRequest. Stamped on every event the bridge emits for that
   * turn so producers can correlate server-side state with their outbound
   * request. Empty for events outside a turn (session_state, system, etc.)
   * and for turns where the caller didn't supply one.
   */
  client_request_id?: string;
  /**
   * TurnID is the bridge-server-minted identifier for an entire turn —
   * from a user_message through every event it produces (init,
   * task_progress, one or more assistant message bubbles, tool calls,
   * etc.) until the terminating result/error. Coarser than MessageID,
   * which scopes to a single message bubble. Empty between turns.
   */
  turn_id?: string;
  /**
   * MessageID is the canonical bridge-server-assigned identifier for the
   * chat message this event belongs to (ULID, "msg_…"). Stable across SSE
   * reconnects and harness restarts. Empty for bookkeeping events
   * (system, session_state, session_info, harness_id_set) that do not
   * belong to a user-visible message bubble.
   */
  message_id?: string;
  /**
   * HarnessMessageID is the harness-native identifier for the same logical
   * message (e.g. Claude Code's msg_…). Used for reconciliation when a
   * harness resumes and re-emits prior messages. Empty when the harness
   * does not surface one.
   */
  harness_message_id?: string;
  timestamp: string;
  /**
   * Content — at most one of these will be populated based on Type.
   */
  result?: ResultEvent;
  stream?: HarnessStream;
  block?: BlockEvent;
  tool_call?: ToolCallEvent;
  tool_result?: ToolResultEvent;
  thinking?: ThinkingEvent;
  plan?: PlanEvent;
  system?: SystemEvent;
  approval?: ApprovalEvent;
  error?: ErrorEvent;
  state?: StateEvent;
  info?: SessionInfo;
  hook?: HookEvent;
  /**
   * Deprecated: AgentState was a coarser projection of SessionState. With
   * SessionState extended to 13 values, the projection is no longer needed.
   * Consumers should switch on State (StateEvent) directly. Field kept
   * during the migration window so existing emitters compile.
   */
  agent_state?: AgentStateEvent;
  usage_total?: UsageTotalEvent;
  turn_complete?: TurnCompleteEvent;
  /**
   * DerivedFrom lists the upstream event ids this event was synthesized
   * from, when llm-bridge-server (or a harness) emits a convenience event
   * derived from one or more raw events. Empty when the event is a
   * first-class observation rather than a derivation. Used by consumers
   * that want to retract or dedupe derived events.
   */
  derived_from?: string[];
  /**
   * Raw preserves the original event JSON from the harness for pass-through.
   */
  raw?: Record<string, unknown>;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * ResultEvent is a completed harness run. Also reused as the payload for
 * EventUserMessage events to record what the user sent: Text holds plain-text
 * input; Blocks holds multimodal input (text/image/document/audio/video).
 * The two are mutually exclusive at the request boundary.
 */
export interface ResultEvent {
  text: string;
  blocks?: ContentBlock[];
  message?: Message;
  is_error?: boolean;
  structured_output?: Record<string, unknown>;
  usage: TokenUsage;
  cost?: Cost;
  duration_ms?: number /* int64 */;
  duration_api_ms?: number /* int64 */;
  num_turns?: number /* int */;
  api_calls?: number /* int */;
  model?: string;
  api_call_usages?: TokenUsage[];
  tool_events?: ToolSummary[];
}
/**
 * ToolSummary records a tool invocation within a completed run.
 */
export interface ToolSummary {
  tool: string;
  input?: string;
  output?: string;
  error?: string;
}
/**
 * HarnessStream is a streaming text/content event from the harness.
 * Named HarnessStream to avoid collision with StreamEvent (API-level streaming).
 * EventStream carries true incremental deltas (token chunks, partial JSON,
 * thinking summary chunks). Whole finished content blocks ride EventBlock
 * instead — see BlockEvent. A harness emits EventStream only when it has
 * granular streaming enabled (e.g. Claude Code with --include-partial-messages).
 */
export interface HarnessStream {
  delta?: BlockDelta;
  message_id?: string;
  hidden?: boolean;
}
/**
 * BlockEvent carries one finished content block from a harness assistant
 * message. Distinct from EventStream: EventBlock is one-shot per completed
 * block (the block has stopped accumulating); EventStream is incremental.
 * Block is the discriminated-union content carrier from msg/content.go,
 * covering text, thinking, tool_use, tool_result, images, etc. — every
 * content variant a harness might surface.
 * MessageID is the harness-native id of the assistant message containing
 * this block (e.g. Claude Code's msg_…), used for grouping multiple blocks
 * from the same model turn into one chat bubble. Index matches the block's
 * position in the original message's content array.
 */
export interface BlockEvent {
  index: number /* int */;
  message_id?: string;
  block?: ContentBlock;
}
/**
 * ToolCallEvent is a tool being invoked.
 * MessageID is the harness-native id of the assistant bubble that contained
 * this tool_use block (e.g. Claude Code's msg_…). It's the same id the
 * surrounding text/thinking events carry on HarnessStream.MessageID — so the
 * bridge server can group tool_call events into their bubble without parsing
 * the raw harness payload.
 */
export interface ToolCallEvent {
  tool_id: string;
  name: string;
  input: Record<string, unknown>;
  message_id?: string;
}
/**
 * ToolResultEvent is the output of a tool invocation.
 * MessageID mirrors ToolCallEvent.MessageID — the harness-native id of the
 * bubble that contained the tool_result block.
 */
export interface ToolResultEvent {
  tool_id: string;
  name: string;
  output: string;
  is_error?: boolean;
  message_id?: string;
}
/**
 * ThinkingEvent is a thinking/reasoning event.
 */
export interface ThinkingEvent {
  text: string;
  subtype?: string; // "", "summary"
}
/**
 * PlanEvent is a structured task-planning event (distinct from thinking).
 */
export interface PlanEvent {
  text: string;
}
/**
 * SystemEvent is a system-level notification.
 * ToolUseID / TaskID / Description / LastToolName are populated for the
 * "task_progress" subtype (Claude Code's narration of an in-flight tool
 * call). ToolUseID is the harness-native tool id (e.g. Anthropic's
 * toolu_…) — the bridge server uses it to resolve the event back to the
 * containing message bubble and stamp MessageID/HarnessMessageID.
 */
export interface SystemEvent {
  subtype: string;
  message?: string;
  attempt?: number /* int */;
  max_retries?: number /* int */;
  retry_delay_ms?: number /* int */;
  error_status?: number /* int */;
  error_type?: string;
  tool_use_id?: string;
  task_id?: string;
  description?: string;
  last_tool_name?: string;
}
/**
 * ApprovalEvent represents a permission request or response.
 * Deprecated: emit HookEvent with Source="permission_prompt" and the
 * awaiting_resolution / completed phase pair instead. Kept this cycle so
 * existing harnesses can transition; consumers should treat both as the same
 * signal. Will be removed in a future release.
 */
export interface ApprovalEvent {
  action: string;
  status: string;
  tool_name?: string;
  detail?: string;
  command?: string;
  path?: string;
  patch?: string;
  permissions?: string[];
  prompt?: string;
}
/**
 * ErrorEvent represents a harness-level error.
 */
export interface ErrorEvent {
  code: string;
  message: string;
  retryable?: boolean;
  status_code?: number /* int */;
}
/**
 * StateEvent represents a session state change.
 */
export interface StateEvent {
  state: SessionState;
  previous?: SessionState;
  reason?: string;
}
/**
 * AgentState was a coarser UI-projection of session lifecycle (4 values).
 * Deprecated: SessionState now carries the full UI vocabulary (13 values)
 * that AgentState was projecting toward. Consumers should switch on
 * SessionState directly via StateEvent. Type kept during the migration
 * window so existing references compile; will be removed once
 * llm-bridge-server stops emitting EventAgentState and consumers migrate.
 */
export type AgentState = string;
export const AgentStateIdle: AgentState = "idle"; // Deprecated: use SessionIdle
export const AgentStateAwaitingInput: AgentState = "awaiting_input"; // Deprecated: use SessionAwaitingUser or SessionAwaitingPermission
export const AgentStateToolRunning: AgentState = "tool_running"; // Deprecated: use SessionToolRunning or SessionModelGenerating
export const AgentStateError: AgentState = "error"; // Deprecated: use SessionError
/**
 * AgentStateEvent is the body for EventAgentState.
 * Deprecated: see AgentState above.
 */
export interface AgentStateEvent {
  state: AgentState;
  previous?: AgentState;
  reason?: string; // free-form, e.g. "tool=Bash", "approval_required"
}
/**
 * UsageTotalEvent is the body for EventUsageTotal. Carries the running
 * session totals, not a delta — emitted once after every ResultEvent
 * fan-out. ContextTokens / ContextLimit on Usage are last-value-wins
 * (state, not consumption); all other TokenUsage fields are summed.
 */
export interface UsageTotalEvent {
  usage: TokenUsage; // cumulative across every result event in this session
  cost?: Cost; // sum where reported; nil until any priced turn lands
  turns: number /* int */; // how many completed turns contributed
}
/**
 * TurnCompleteEvent is the body for EventTurnComplete. Emitted once per
 * turn, immediately after the terminating ResultEvent (or ErrorEvent for
 * error-terminated turns) is fanned out. TurnID matches the originating
 * user_message's turn_id.
 */
export interface TurnCompleteEvent {
  turn_id: string; // matches the originating user_message's turn_id
  final_message?: string; // last assistant text in the turn (from ResultEvent.Text)
  tool_calls?: ToolSummary[]; // every tool_call/tool_result pair seen in this turn
  usage_delta: TokenUsage; // this turn's contribution
  cost?: Cost;
  duration_ms: number /* int64 */; // wall-clock from user_message → result
  is_error?: boolean;
  error_message?: string;
}
/**
 * SessionInfo describes what the harness knows about its session at start:
 * the system prompt it was configured with, the working directory, and the
 * tools / slash commands / sub-agents / MCP servers the underlying agent
 * reports as available. Emitted by the harness as an EventSessionInfo after
 * the agent's initial handshake, and persisted on ManagedSession so it can
 * be retrieved via GET /sessions/{id} without replaying events.
 */
export interface SessionInfo {
  system_prompt?: string;
  append_system_prompt?: string;
  working_dir?: string;
  model?: string;
  permission_mode?: string;
  tools?: ToolInfo[];
  slash_commands?: string[];
  agents?: string[];
  skills?: string[];
  mcp_servers?: MCPServerInfo[];
}
/**
 * ToolInfo names a tool the agent has available. Description is optional —
 * the harness only reports what the underlying agent exposes; the UI may
 * enrich with its own descriptions.
 */
export interface ToolInfo {
  name: string;
  description?: string;
}
/**
 * MCPServerInfo describes an MCP server connection reported by the agent.
 */
export interface MCPServerInfo {
  name: string;
  status?: string;
}
/**
 * HookEvent records a harness hook lifecycle event.
 * Three sources produce HookEvents, discriminated by Source / HookID:
 *  1. Harness-native observation (Source empty or "hook", HookID empty) — the
 *     underlying harness emits its own hook lifecycle notifications (e.g.
 *     Claude Code with --include-hook-events) and the bridge translates them.
 *     The bridge has no control over these hooks.
 *  2. Bridge-registered invocation (Source empty or "hook", HookID set) — a
 *     hook registered with the hook-store fires via the harness's native
 *     mechanism, which shells out to the bridge server's /hooks/exec/{id}
 *     endpoint.
 *  3. Permission-prompt invocation (Source="permission_prompt") — the harness
 *     wired a permission-prompt callback (e.g. Claude Code's
 *     --permission-prompt-tool MCP server) and is consulting the bridge for a
 *     tool-use decision. Functionally a synthetic PreToolUse hook whose
 *     resolver is human (or shell or auto) per the bridge's settings.
 * Input and Output are raw JSON, passed through in the underlying harness's
 * native dialect (e.g. Claude Code's stdin/stdout hook protocol). Layers are
 * transparent: no translation into a neutral schema.
 */
export interface HookEvent {
  /**
   * Event names the hook lifecycle point (e.g. "PreToolUse", "PostToolUse",
   * "UserPromptSubmit"). Values match the underlying harness's native event
   * names — no rewriting.
   */
  event: string;
  /**
   * Matcher is the harness-native matcher that selected this hook (for
   * Claude Code: the tool-name pattern like "Bash" or "Edit|Write"). Empty
   * when the hook applies to all events of its type or when the harness
   * does not expose a matcher concept.
   */
  matcher?: string;
  /**
   * ToolName is the tool the hook fired against, when applicable
   * (PreToolUse, PostToolUse). Empty for non-tool-scoped events.
   */
  tool_name?: string;
  /**
   * HookID is the bridge-registry id of the hook, when the event came from
   * a hook registered with the bridge's hook-store. Empty for harness-native
   * (observation-only) hooks that the bridge did not register.
   */
  hook_id?: string;
  /**
   * Source discriminates the emission origin: "hook" (harness-native or
   * bridge-registered hook; default when empty) or "permission_prompt"
   * (harness's permission-prompt callback). Determines which decision
   * protocol applies on resolution.
   */
  source?: string;
  /**
   * Phase is the lifecycle point: "started", "progress", "completed", or
   * "awaiting_resolution". Most hook invocations produce a "started" and a
   * "completed" event; long-running hooks may emit "progress" between.
   * Hooks that defer to a human resolver (or any out-of-band resolver)
   * emit "awaiting_resolution" between "started" and "completed" — the
   * matching "completed" event carries Resolution and shares RequestID.
   */
  phase: string;
  /**
   * RequestID correlates an awaiting_resolution event with its eventual
   * completed event. Set on phase="awaiting_resolution" and on the matching
   * phase="completed" emitted once the resolver decides. Empty for hooks
   * that complete synchronously without an external resolver.
   */
  request_id?: string;
  /**
   * Input is the raw JSON the harness passed to the hook (stdin payload for
   * Claude Code; tool input JSON for permission-prompt). Populated on
   * Phase="started" and Phase="awaiting_resolution". Pass-through.
   */
  input?: Record<string, unknown>;
  /**
   * Output is the raw JSON the hook returned to the harness (stdout payload
   * for Claude Code). Populated on Phase="completed". Pass-through.
   */
  output?: Record<string, unknown>;
  /**
   * Decision summarizes the hook's effect on the tool call when the harness
   * surfaces one (e.g. Claude Code's "allow", "deny", "modify", "continue").
   * Empty when the harness does not report a decision.
   */
  decision?: string;
  /**
   * Resolution captures how an awaiting_resolution hook was resolved.
   * Populated on Phase="completed" when a prior awaiting_resolution event
   * existed for the same RequestID. Nil for hooks that completed without
   * going through awaiting_resolution.
   */
  resolution?: HookResolution;
  /**
   * ExitCode is the exit status of the hook command when the harness
   * reports one (Claude Code does, on Phase="completed").
   */
  exit_code?: number /* int */;
  /**
   * DurationMS is the wall-clock time the hook took to run. Populated on
   * Phase="completed" when the harness reports timing.
   */
  duration_ms?: number /* int64 */;
  /**
   * Error is a non-empty message when the hook failed to execute or
   * returned malformed output. An errored hook may still carry Output if
   * the harness produced something before failing.
   */
  error?: string;
}
/**
 * HookResolution captures the decision that closed an awaiting_resolution hook.
 */
export interface HookResolution {
  /**
   * Behavior is "allow" or "deny". Required.
   */
  behavior: string;
  /**
   * UpdatedInput, if non-nil, is the input the harness should run instead
   * of the original Input. Only meaningful for permission-prompt-style
   * hooks where the underlying harness supports input substitution
   * (e.g. Claude Code's permission-prompt-tool returning updatedInput).
   */
  updated_input?: Record<string, unknown>;
  /**
   * Message is an optional explanation forwarded to the harness (and shown
   * alongside denied calls in the UI).
   */
  message?: string;
  /**
   * ResolvedBy identifies the resolver that decided: "user", "shell:<cmd>",
   * "auto", "allow_always". Informational; consumers should not branch on
   * it for correctness.
   */
  resolved_by?: string;
}

//////////
// source: hook.go

/**
 * HookScope identifies the resolution layer a hook lives on.
 * Hooks compose: a session inherits every enabled hook whose scope
 * matches, across all three layers. When two scopes register a hook with
 * the same (harness, event, matcher), the most specific scope wins:
 * session > instance > global.
 */
export type HookScope = string;
export const HookScopeGlobal: HookScope = "global"; // applies to every session
export const HookScopeInstance: HookScope = "instance"; // applies to every session on an instance
export const HookScopeSession: HookScope = "session"; // applies to one specific session
/**
 * Hook is a registered hook handler. Each Hook describes one (event, matcher)
 * pair on one harness, bound to a local shell command that runs when the
 * underlying harness fires the event. The command receives the harness's
 * native hook stdin and returns the harness's native hook stdout — the bridge
 * does not translate either direction.
 * For Claude Code: the command is wired into a synthesized settings JSON
 * (passed to `claude` via --settings) when a session spawns. When CC invokes
 * the hook, it shells out to the bridge server's /hooks/exec/{id} endpoint,
 * which executes Command with stdin/stdout pass-through.
 */
export interface Hook {
  id: string; // ULID
  harness: Harness; // claudecode, codex, ...
  event: string; // harness-native event name (PreToolUse, etc.)
  /**
   * Matcher is the harness-native matcher that scopes the hook to a subset
   * of events (for Claude Code: a tool-name pattern like "Bash" or
   * "Edit|Write"). Empty matches everything the harness delivers for Event.
   */
  matcher?: string;
  /**
   * Command is the local shell command that runs when the hook fires.
   * Executed via `sh -c <Command>`. Stdin is the harness-native hook input
   * payload; stdout is the harness-native response. No wrapping, no
   * translation — the handler speaks the harness's dialect directly.
   */
  command: string;
  scope_kind: HookScope;
  /**
   * ScopeID is the instance id or session id the hook is bound to. Empty
   * for HookScopeGlobal.
   */
  scope_id?: string;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}

//////////
// source: instance.go

/**
 * Transport specifies how a harness subprocess is reached on its host.
 */
export type Transport = string;
export const TransportLocal: Transport = "local"; // local subprocess on the same host as llm-bridge-server
export const TransportSSH: Transport = "ssh"; // SSH from server to remote machine, server forks subprocess via sshd
export const TransportRunner: Transport = "runner"; // remote llm-bridge-runner daemon dialed in over WebSocket
/**
 * Machine represents a host where harness subprocesses can run. One row per
 * physical/virtual host. Multiple instances may share a machine (e.g.
 * claude_code and codex on the same laptop). Created either explicitly
 * (local/ssh) or auto-created when an llm-bridge-runner enrolls.
 */
export interface Machine {
  id: string; // m_<id>
  name: string; // unique, human label: "linode", "wsl-claude"
  emoji?: string; // optional UI accent: 🏠 🖥 ☁ etc.
  hostname?: string; // network address (Tailscale name, IP, …); empty for runner
  os?: string; // GOOS reported by runner, or set on create
  arch?: string; // GOARCH
  transport: Transport;
  ssh_user?: string;
  ssh_key_path?: string;
  ssh_port?: number /* int */; // default 22
  default_working_dir?: string;
  user?: string; // runner-side OS user (display only)
  notes?: string;
  last_seen_at?: string;
  created_at: string;
  updated_at: string;
}
/**
 * Instance represents a configured harness deployment on a machine. The
 * Machine pointer is populated by API responses for client convenience;
 * internal storage code reads from the machines table directly.
 */
export interface Instance {
  id: string;
  harness_type: Harness;
  name: string;
  machine_id: string;
  working_dir?: string; // overrides Machine.DefaultWorkingDir for this instance
  max_concurrent_sessions: number /* int */;
  enabled: boolean;
  created_at: string;
  updated_at: string;
  /**
   * Machine is populated by API responses (denormalized for the client).
   * Storage and routing code looks up the machine by ID directly.
   */
  machine?: Machine;
}
/**
 * InstanceCredential binds a credential to a harness instance with priority.
 */
export interface InstanceCredential {
  instance_id: string;
  credential_id: string;
  priority: number /* int */; // 0 = primary, 1+ = fallbacks
  enabled: boolean;
}
/**
 * InstanceStatus aggregates runtime status for an instance.
 */
export interface InstanceStatus {
  instance: Instance;
  active_sessions: number /* int */;
  credentials: InstanceCredential[];
  reachable: boolean; // SSH/runner connectivity check
  last_checked: string;
}
/**
 * RunnerEnrollment is a one-time-use token that lets a runner self-register
 * a Machine without prior server-side configuration. Minted by an admin
 * (CLI or API), redeemed by the runner via POST /api/runner/enroll.
 */
export interface RunnerEnrollment {
  id: string; // enr_<id>
  expires_at: string;
  used_at?: string; // zero if unused
  consumed_machine_id?: string; // set when redeemed
  created_at: string;
}

//////////
// source: message.go

/**
 * Conversation represents a complete request to an LLM API.
 */
export interface Conversation {
  id?: string;
  model: string;
  provider: Provider;
  /**
   * System prompt — always a slice of content blocks, never a bare string.
   */
  system?: ContentBlock[];
  messages: Message[];
  tools?: ToolDef[];
  tool_choice?: ToolChoice;
  config: GenerationConfig;
  provider_config?: Record<string, unknown>; // AnthropicConfig | OpenAIConfig | GeminiConfig | OpenRouterConfig
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   * Keys are namespaced by bridge (e.g. "anthropic:beta_feature").
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * Message is a single turn in a conversation.
 */
export interface Message {
  id?: string;
  role: Role;
  /**
   * Content is always a slice of typed blocks.
   */
  content: ContentBlock[];
  /**
   * Name is an optional participant identifier (OpenAI supports this).
   */
  name?: string;
  /**
   * NativeRole preserves the original provider role for lossless round-trip.
   */
  native_role?: NativeRole;
  /**
   * SourcePattern records how this message was originally structured for round-trip.
   */
  source_pattern?: string;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}

//////////
// source: provider.go

/**
 * Provider identifies which LLM API produced or will consume a message.
 */
export type Provider = string;
export const ProviderAnthropic: Provider = "anthropic";
export const ProviderOpenAI: Provider = "openai";
export const ProviderGemini: Provider = "gemini";
export const ProviderOpenRouter: Provider = "openrouter";
/**
 * Role is the normalized message role across all providers.
 */
export type Role = string;
export const RoleSystem: Role = "system";
export const RoleUser: Role = "user";
export const RoleAssistant: Role = "assistant";
export const RoleTool: Role = "tool";
/**
 * NativeRole maps to provider-specific role strings.
 */
export interface NativeRole {
  provider: Provider;
  value: string; // e.g. "model" for Gemini, "developer" for OpenAI o-series
}
/**
 * StopReason is the normalized reason a completion ended.
 */
export type StopReason = string;
export const StopEnd: StopReason = "end";
export const StopMaxTokens: StopReason = "max_tokens";
export const StopToolUse: StopReason = "tool_use";
export const StopStopSequence: StopReason = "stop_sequence";
export const StopSafety: StopReason = "safety";
export const StopContentFilter: StopReason = "content_filter";
export const StopRecitation: StopReason = "recitation";
export const StopError: StopReason = "error";
/**
 * Harness identifies which agent harness produced an event.
 */
export type Harness = string;
export const HarnessClaudeCode: Harness = "claude_code";
export const HarnessCodex: Harness = "codex";
export const HarnessOpenClaw: Harness = "openclaw";
export const HarnessInber: Harness = "inber";
export const HarnessHermes: Harness = "hermes";
export const HarnessAider: Harness = "aider";
export const HarnessGoose: Harness = "goose";
export const HarnessAutohand: Harness = "autohand";
export const HarnessJig: Harness = "jig";
export const HarnessDexto: Harness = "dexto";
export const HarnessCommander: Harness = "commander";
export const HarnessNanoClaw: Harness = "nanoclaw";
export const HarnessCline: Harness = "cline";
export const HarnessRooCode: Harness = "roo_code";
export const HarnessKiloCode: Harness = "kilo_code";
export const HarnessOpenCode: Harness = "opencode";
export const HarnessForgecode: Harness = "forgecode";
export const HarnessGemini: Harness = "gemini";
/**
 * EventType classifies a harness event.
 */
export type EventType = string;
export const EventResult: EventType = "result";
export const EventStream: EventType = "stream";
export const EventBlock: EventType = "block";
export const EventToolCall: EventType = "tool_call";
export const EventToolResult: EventType = "tool_result";
export const EventThinking: EventType = "thinking";
export const EventSystem: EventType = "system";
export const EventApproval: EventType = "approval";
export const EventError: EventType = "error";
export const EventSessionState: EventType = "session_state";
export const EventPlan: EventType = "plan";
export const EventSessionInfo: EventType = "session_info";
export const EventUserMessage: EventType = "user_message";
export const EventHook: EventType = "hook";
/**
 * Convenience events — derived centrally by llm-bridge-server from
 * the raw event stream. Distinct from EventSessionState (the harness
 * lifecycle) because agent_state is the coarser UI projection. See
 * msg/CONVENIENCE-EVENTS.md.
 */
export const EventAgentState: EventType = "agent_state";
export const EventUsageTotal: EventType = "usage_total";
export const EventTurnComplete: EventType = "turn_complete";
/**
 * SessionState represents the current state of an llm-bridge-managed
 * session. Authoritative values are derived centrally by llm-bridge-server
 * from the raw event stream plus server-only context (pause/abort calls,
 * permission-store hook state, subprocess lifecycle, provider rate-limit
 * signals). Harnesses no longer emit SessionState directly — they emit
 * raw actions (tool_call, tool_result, block, hook, error) and the server
 * computes the state.
 */
export type SessionState = string;
/**
 * Pre-flight.
 */
export const SessionStarting: SessionState = "starting"; // subprocess spawned, no first event yet
/**
 * Active (agent is working).
 */
export const SessionModelGenerating: SessionState = "model_generating"; // assistant streaming tokens
export const SessionToolRunning: SessionState = "tool_running"; // tool call in flight
export const SessionCompacting: SessionState = "compacting"; // context compaction in progress
/**
 * Blocked on user (action required).
 */
export const SessionAwaitingPermission: SessionState = "awaiting_permission"; // hook prompt open, blocking on approve/deny
export const SessionAwaitingUser: SessionState = "awaiting_user"; // turn ended, expects user reply (best-effort heuristic)
/**
 * Self-healing wait (no action; will resume).
 */
export const SessionRateLimited: SessionState = "rate_limited"; // provider backoff
export const SessionPaused: SessionState = "paused"; // user-interrupted, can be resumed
/**
 * Quiet but alive.
 */
export const SessionIdle: SessionState = "idle"; // between turns, no terminal signal
/**
 * Terminal.
 */
export const SessionCompleted: SessionState = "completed"; // agent signaled work done
export const SessionError: SessionState = "error"; // last activity ended in error
export const SessionAborted: SessionState = "aborted"; // killed by user/system (intentional)
export const SessionDisconnected: SessionState = "disconnected"; // process gone unexpectedly (no clean exit)
/**
 * Deprecated: replaced by SessionModelGenerating / SessionToolRunning.
 * Kept valid during the migration window so harness packages that still
 * emit EventSessionState continue to compile. Will be removed once all
 * llm-bridge-* harnesses stop emitting SessionState.
 */
export const SessionRunning: SessionState = "running";
/**
 * Deprecated: renamed to SessionAwaitingPermission. Kept valid during
 * the migration window for the same reason as SessionRunning above.
 */
export const SessionWaitingApproval: SessionState = "waiting_on_approval";

//////////
// source: response.go

/**
 * CompletionResponse is the unified response from any LLM API.
 */
export interface CompletionResponse {
  id: string;
  model: string;
  provider: Provider;
  message: Message;
  stop_reason: StopReason;
  native_stop_reason: string;
  stop_sequence?: string;
  usage: TokenUsage;
  cost?: Cost;
  /**
   * Gemini: per-response safety ratings.
   */
  safety_ratings?: SafetyRating[];
  /**
   * OpenAI: server-side configuration fingerprint.
   */
  system_fingerprint?: string;
  /**
   * OpenAI: logprobs for the response tokens.
   */
  logprobs?: LogProbs;
  /**
   * OpenAI: multiple choices when n > 1.
   */
  additional_choices?: CompletionChoice[];
  /**
   * Raw is the complete original provider JSON response.
   * Preserved for debugging and detecting data missed by the bridge.
   */
  raw?: Record<string, unknown>;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   * Keys are namespaced by bridge (e.g. "anthropic:beta_feature", "openai:service_tier").
   * This allows bridges to pass through new features before the spec adds official support.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * CompletionChoice represents one of potentially multiple completions (OpenAI n > 1).
 */
export interface CompletionChoice {
  index: number /* int */;
  message: Message;
  stop_reason: StopReason;
  native_stop_reason: string;
}
/**
 * SafetyRating is a Gemini per-category safety assessment.
 */
export interface SafetyRating {
  category: string;
  probability: string;
  blocked?: boolean;
}
/**
 * SafetySetting configures Gemini safety thresholds.
 */
export interface SafetySetting {
  category: string;
  threshold: string;
}
/**
 * LogProbs contains OpenAI token log probability data.
 */
export interface LogProbs {
  content?: TokenLogProb[];
}
/**
 * TokenLogProb is the log probability for a single token.
 */
export interface TokenLogProb {
  token: string;
  logprob: number /* float64 */;
  bytes?: number /* int */[];
  top_logprobs?: TopLogProb[];
}
/**
 * TopLogProb is one of the top-k alternative tokens.
 */
export interface TopLogProb {
  token: string;
  logprob: number /* float64 */;
  bytes?: number /* int */[];
}

//////////
// source: runner.go

/**
 * RunnerMessageType discriminates the polymorphic RunnerMessage envelope.
 */
export type RunnerMessageType = string;
/**
 * Connection-level (no SessionID).
 */
export const RunnerMsgHello: RunnerMessageType = "hello"; // runner → server, sent immediately after connect
export const RunnerMsgWelcome: RunnerMessageType = "welcome"; // server → runner, ack
export const RunnerMsgError: RunnerMessageType = "error"; // either direction, fatal error before close
export const RunnerMsgPing: RunnerMessageType = "ping"; // app-level keepalive (in addition to WS pings)
export const RunnerMsgPong: RunnerMessageType = "pong";
/**
 * Per-session (SessionID required).
 */
export const RunnerMsgSpawn: RunnerMessageType = "spawn"; // server → runner
export const RunnerMsgStdin: RunnerMessageType = "stdin"; // server → runner
export const RunnerMsgSignal: RunnerMessageType = "signal"; // server → runner
export const RunnerMsgStdout: RunnerMessageType = "stdout"; // runner → server
export const RunnerMsgStderr: RunnerMessageType = "stderr"; // runner → server
export const RunnerMsgExit: RunnerMessageType = "exit"; // runner → server
/**
 * Seeding (no SessionID; carry context/skill files from the bridge to the runner).
 */
export const RunnerMsgSeedDelta: RunnerMessageType = "seed_delta"; // server → runner, single-file delta (push)
export const RunnerMsgSeedSnapshot: RunnerMessageType = "seed_snapshot"; // server → runner, full manifest snapshot (after scan)
/**
 * RunnerMessage is the envelope for every frame exchanged on the runner WS.
 * Exactly one payload field is populated, matching Type.
 */
export interface RunnerMessage {
  type: RunnerMessageType;
  session_id?: string;
  hello?: RunnerHello;
  welcome?: RunnerWelcome;
  error?: RunnerError;
  spawn?: RunnerSpawn;
  stdin?: RunnerStdin;
  stdout?: RunnerStdout;
  stderr?: RunnerStderr;
  signal?: RunnerSignal;
  exit?: RunnerExit;
  seed_delta?: RunnerSeedDelta;
  seed_snapshot?: RunnerSeedSnapshot;
}
/**
 * RunnerHello is sent by the runner immediately after the WS upgrade.
 * Authentication is the Authorization: Bearer header on the upgrade
 * request — the server resolves the token to a Machine row by hash.
 * The Hello payload is environmental detail the server records for
 * display + binary-serving (hostname, OS, etc.); it carries no identity
 * claims of its own. The machine label is server-side state, returned
 * to the runner via Welcome.MachineName.
 */
export interface RunnerHello {
  hostname: string; // os.Hostname()
  os: string; // GOOS
  arch: string; // GOARCH
  user: string; // os/user.Current().Username
  working_dir: string; // default cwd for spawned subprocesses
  available_harnesses: HarnessAvailable[]; // detected harness binaries on this machine
  runner_version: string; // build-stamped version
}
/**
 * HarnessAvailable reports a harness binary present on the runner machine.
 */
export interface HarnessAvailable {
  harness: Harness;
  binary: string; // absolute path
  version?: string;
}
/**
 * RunnerWelcome is the server's ack of a successful Hello.
 * MachineName is the canonical name on the server side. Runners with a
 * stale local label (e.g. machine renamed in the UI after enrollment)
 * should overwrite their saved config from this value so subsequent
 * connects don't keep reporting the old name.
 */
export interface RunnerWelcome {
  machine_id: string; // server-assigned, stable across reconnects
  machine_name: string; // authoritative current name
  server_version: string;
  ping_interval_secs: number /* int */; // app-level ping cadence the runner should follow
  accepted_at: string;
}
/**
 * RunnerError reports a fatal error before the connection is closed.
 * Code is a stable machine-readable token; Message is human prose.
 */
export interface RunnerError {
  code: string; // "auth_failed", "duplicate_machine", "internal", …
  message: string;
}
/**
 * RunnerSpawn asks the runner to fork a harness subprocess for a session.
 * StartParams is the same payload the local subprocess transport sends to
 * the harness as the "start" JSON-RPC method — the runner writes it
 * verbatim to the subprocess's stdin as the first line.
 * Provision lists long-lived backend services the wrapper expects to be
 * running on the same host (e.g. inber-server for the inber wrapper).
 * The runner ensures each is installed and running before the fork —
 * idempotently, so subsequent spawns don't restart a healthy backend.
 * This is how "create an instance on a remote machine" actually
 * deploys the harness's full stack to that machine.
 */
export interface RunnerSpawn {
  harness: Harness;
  binary_path?: string; // optional override; runner falls back to PATH lookup
  working_dir?: string; // overrides Hello.WorkingDir for this session
  start_params: Record<string, unknown>; // verbatim JSON-RPC params for "start"
  env?: string[]; // extra env vars for the wrapper, "KEY=VALUE" form
  provision?: HarnessService[]; // backend services the runner should ensure are running
}
/**
 * HarnessService describes one long-lived backend daemon a harness needs
 * running on the runner host. The bridge populates this from its own
 * per-harness deployment manifest, with credential values already
 * resolved into Env so the runner doesn't need bridge-side state.
 */
export interface HarnessService {
  name: string; // unique key, e.g. "inber-server"; runners dedupe by this across spawns
  binary_url: string; // canonical /api/runner/binary?name=…&os=…&arch=… URL
  binary_path?: string; // absolute path on the runner; defaults to ~/.local/bin/<name>
  args?: string[]; // command-line args passed to the binary
  env?: string[]; // env vars (KEY=VALUE), including resolved credential values
  health_url: string; // GET probe to wait for after start (e.g. http://localhost:8200/health)
  stdout?: string; // optional log file path; defaults to ~/.cache/llm-bridge-runner/<name>.log
}
/**
 * RunnerStdin carries one line (no trailing newline) of NDJSON to be
 * written to the subprocess stdin, with a newline appended by the runner.
 */
export interface RunnerStdin {
  data: string;
}
/**
 * RunnerStdout carries one line (no trailing newline) read from the
 * subprocess stdout. The server's existing pipeline parses it as msg.Event.
 */
export interface RunnerStdout {
  data: string;
}
/**
 * RunnerStderr carries one line of subprocess stderr, forwarded for
 * server-side logging. Not parsed.
 */
export interface RunnerStderr {
  data: string;
}
/**
 * RunnerSignalType is the kind of signal to deliver to a subprocess.
 */
export type RunnerSignalType = string;
export const RunnerSignalInterrupt: RunnerSignalType = "interrupt"; // SIGINT, pause/cancel current turn
export const RunnerSignalKill: RunnerSignalType = "kill"; // SIGKILL, terminate immediately
/**
 * RunnerSignal asks the runner to deliver a signal to a session's subprocess.
 */
export interface RunnerSignal {
  signal: RunnerSignalType;
}
/**
 * RunnerExit reports that a session's subprocess has exited.
 */
export interface RunnerExit {
  exit_code: number /* int */;
  error?: string; // non-empty if the process couldn't be reaped cleanly
}
/**
 * SeedSource discriminates which store provided a seeded file. Lets the
 * runner reconcile each provider against its own endpoint set without the
 * bridge needing per-source message types.
 */
export type SeedSource = string;
export const SeedSourceAgentStore: SeedSource = "agent-store"; // CLAUDE.md, AGENTS.md, memory, subagents, …
export const SeedSourceSkillStore: SeedSource = "skill-store"; // ~/.claude/skills/**
/**
 * SeedOp is the kind of change the runner should apply to a seeded path.
 */
export type SeedOp = string;
export const SeedOpUpsert: SeedOp = "upsert"; // create or overwrite (drift-checked)
export const SeedOpDelete: SeedOp = "delete"; // remove (only if locally still equals last-pushed sha)
/**
 * RunnerSeedDelta is a single-file change pushed to a runner immediately
 * after the bridge records a new authoritative version. The runner must:
 *  1. Compute the sha256 of the local file at InstallPath, if any.
 *  2. If the local sha differs from ExpectedPriorSHA (drift), POST the local
 *     bytes to the source's /seed/drift endpoint *first*. Only if that call
 *     succeeds may it proceed to step 3.
 *  3. GET the new content from the source's version endpoint and write it
 *     atomically (tmp + rename).
 * ExpectedPriorSHA empty = the runner has never seen this file (first push).
 * In that case any pre-existing content at InstallPath is treated as drift.
 */
export interface RunnerSeedDelta {
  source: SeedSource;
  op: SeedOp;
  tracked_id: number /* int64 */; // ID in the source store
  version_id?: number /* int64 */; // version to fetch on upsert
  install_path: string; // $HOME-relative
  new_sha?: string; // sha of the new content (upsert only)
  expected_prior_sha?: string; // last-pushed sha bridge thinks runner has
}
/**
 * RunnerSeedSnapshot tells the runner to do a full manifest reconcile against
 * the named source. Sent on connect and after a bridge-side scan completes.
 * The actual manifest is fetched via HTTP — this message is just the trigger
 * + opportunity to bundle metadata (e.g. ticket count) for telemetry.
 */
export interface RunnerSeedSnapshot {
  source: SeedSource;
  entry_count?: number /* int */; // bridge's count, for sanity logging
  reason?: string; // "connect", "scan", "manual", …
}

//////////
// source: server.go

/**
 * SessionMode selects the I/O contract for a session at spawn time.
 * SessionModeEvents (default) runs the harness in its current structured-
 * events posture: stdin/stdout NDJSON between server and harness, normalized
 * msg.Event stream over GET /sessions/{id}/events.
 * SessionModePTY runs the harness's upstream CLI inside a pseudoterminal
 * the caller attaches to over a WebSocket at GET /sessions/{id}/attach.
 * Bytes pass through verbatim — no msg.Event derivation. Per-harness
 * opt-in via bridge.PTYCapableHarness.
 */
export type SessionMode = string;
export const SessionModeEvents: SessionMode = "events";
export const SessionModePTY: SessionMode = "pty";
/**
 * SessionType categorizes a session by how it is being used. Bridge-side
 * behavior that depends on category (e.g. completion notifications, SSE
 * keepalive policy) reads SessionType. Behavior that depends on which
 * specific service originated the session reads Source.
 * Will be required on Create — the field is currently optional in the wire
 * format for backward compatibility while callers are updated. Enforcement
 * flips on once all callers populate it. See MIGRATION-session-identity.md.
 */
export type SessionType = string;
/**
 * SessionTypeInteractive: human-in-the-loop. Frontend chat, CLI, mobile.
 */
export const SessionTypeInteractive: SessionType = "interactive";
/**
 * SessionTypeAutonomous: fire-and-forget agent runs, no human watching
 * live. Autoworker, scheduler-fired tasks, kanban dispatcher.
 */
export const SessionTypeAutonomous: SessionType = "autonomous";
/**
 * SessionTypeSystem: bridge-internal subsystems and meta-agents.
 * Renamer, subagents, kanban classifier, permission_prompt.
 */
export const SessionTypeSystem: SessionType = "system";
/**
 * ManagedSession is a session as tracked by llm-bridge-server.
 * This is the server's lightweight session management entity, distinct from
 * [Session] which models rich agent-level state (usage, tasks, context).
 * Identifier fields:
 *   - SessionID: canonical session id. Caller-minted on Create or
 *     server-minted (br_<nanos>) when omitted. Stable from creation.
 *   - HarnessSessionID: the canonical harness session ID (e.g. CC UUID).
 *     Rotates on resume/fork. Empty until the harness reports it on first
 *     event. Will move to adapter-private storage in Phase II.C.
 */
export interface ManagedSession {
  session_id: string;
  harness_session_id?: string;
  display_name: string;
  harness: Harness;
  instance_id?: string;
  state: string;
  pid?: number /* int */;
  agent_id?: string;
  spawner_id?: string;
  parent_id?: string;
  harness_config?: Record<string, unknown>; // opaque harness-specific config
  info?: SessionInfo; // latest session info reported by the harness
  folder_name?: string; // user-assigned sidebar folder; empty = unfiled
  source?: string; // origin tag carried from the creator (e.g. "scheduler", "autoworker"); empty = interactive
  session_type?: SessionType; // category of session; required on Create once enforcement flips on
  mode?: SessionMode; // I/O mode picked at creation; empty = events (legacy default)
  created_at: string;
  updated_at: string;
}
/**
 * HarnessAgent is one of the agents registered against a harness type.
 * Surfaced by /harnesses/{name}/capabilities so frontends can offer a
 * per-harness agent picker without re-querying agent-store.
 */
export interface HarnessAgent {
  name: string;
  display_name?: string;
  description?: string;
  is_default?: boolean;
}
/**
 * HarnessInfo describes a registered harness type and its capabilities.
 * HookEvents lists the hook lifecycle events the bridge can register handlers
 * against for this harness (e.g. Claude Code's "PreToolUse", "PostToolUse"…).
 * Empty for harnesses with no registerable hook mechanism — harnesses that
 * only emit observation-style lifecycle notifications or run agents remotely
 * without local hook points.
 */
export interface HarnessInfo {
  name: string;
  label: string;
  emoji: string;
  image?: string;
  /**
   * Tint is a sRGB hex (e.g. "#d97757") used by UIs to key chrome to a
   * specific harness — header washes, chips, etc. Empty when the harness
   * has no canonical color and the UI should fall through to its own
   * theme accent.
   */
  tint?: string;
  available: boolean;
  binary?: string;
  capabilities: string[];
  hook_events?: string[];
  supported_providers?: string[];
  /**
   * PTY reports whether this harness can run inside a pseudoterminal
   * (pty session mode). CLI harnesses with a real subprocess set this
   * true; HTTP-backed harnesses set it false. See bridge.PTYCapableHarness.
   */
  pty: boolean;
}
/**
 * Credential represents an API credential as exposed by the server.
 * Sensitive fields are masked (api_key_masked, token_masked).
 */
export interface Credential {
  id: string;
  provider: string;
  label: string;
  auth_type: string;
  api_key_masked?: string;
  token_masked?: string;
  priority: number /* int */;
  enabled: boolean;
  expires_at: number /* int64 */;
  error_count?: number /* int */;
  last_error?: string;
}
/**
 * HarnessDefaults stores per-harness configuration defaults.
 */
export interface HarnessDefaults {
  model?: string;
  effort?: string;
  max_budget?: number /* float64 */;
  disabled_tools?: string[];
  permission_mode?: string;
}
/**
 * BridgePrefs stores user preferences for the bridge dashboard.
 */
export interface BridgePrefs {
  last_harness?: string;
  last_instance_id?: string;
  last_session?: { [key: string]: string};
  last_instance?: { [key: string]: string};
  defaults?: { [key: string]: HarnessDefaults};
  /**
   * BypassPermissions, when true, makes new sessions launch with
   * --permission-mode bypassPermissions (CC never calls our MCP) AND
   * flips every live MCP into always-allow via /bridge/bypass-permissions.
   * The toggle is on dash /settings; written exclusively through that
   * endpoint (not through PUT /bridge-prefs partial updates) so the
   * bool merge ambiguity doesn't apply.
   */
  bypass_permissions?: boolean;
}
/**
 * MaterializedMessage is a flattened message returned by the messages API.
 * Assembled from raw events by log-store: stream deltas are concatenated,
 * tool calls are collected, and the final ResultEvent becomes Meta.
 */
export interface MaterializedMessage {
  id?: string; // canonical bridge MessageID
  harness_message_id?: string; // harness-native id, if known
  role: string;
  content: string;
  thinking?: string;
  tools?: MaterializedTool[];
  meta?: ResultEvent;
  events?: Record<string, unknown>[];
  timestamp: string;
  done: boolean;
}
/**
 * MaterializedTool records a tool invocation within a materialized message.
 */
export interface MaterializedTool {
  tool_id: string;
  tool: string;
  input?: Record<string, unknown>;
  output?: string;
  error?: boolean;
}
/**
 * SessionAggregate is the per-session token/cost summary returned by
 * GET /api/v1/sessions/aggregates. Computed by SUMming the result events
 * stored for each session — no separate aggregate table. Model is the
 * most recent value reported across the session's result events.
 */
export interface SessionAggregate {
  session_id: string;
  turns: number /* int */;
  input_tokens: number /* int64 */;
  output_tokens: number /* int64 */;
  cost_usd: number /* float64 */;
  duration_ms: number /* int64 */;
  model?: string;
}
/**
 * HealthResponse is the server's health check response.
 */
export interface HealthResponse {
  status: string;
  harnesses: HarnessInfo[];
  sessions: SessionCounts;
}
/**
 * SessionCounts is a breakdown of active sessions by state.
 */
export interface SessionCounts {
  running: number /* int */;
  idle: number /* int */;
  completed: number /* int */;
}
/**
 * ConformanceFeature is a capability that a harness may or may not support.
 */
export type ConformanceFeature = string;
/**
 * ConformanceTestResult records the outcome of a single feature test.
 */
export interface ConformanceTestResult {
  feature: ConformanceFeature;
  passed: boolean;
  skipped?: boolean;
  error?: string;
  duration?: string;
}
/**
 * ConformanceHarnessResult records all test results for a single harness.
 */
export interface ConformanceHarnessResult {
  harness: string;
  binary: string;
  tested_at: string;
  results: ConformanceTestResult[];
  summary: ConformanceSummary;
}
/**
 * ConformanceSummary counts test outcomes.
 */
export interface ConformanceSummary {
  total: number /* int */;
  passed: number /* int */;
  failed: number /* int */;
  skipped: number /* int */;
}
/**
 * ConformanceMatrix holds conformance results for all tested harnesses.
 */
export interface ConformanceMatrix {
  generated_at: string;
  harnesses: ConformanceHarnessResult[];
}
/**
 * CreateSessionRequest is the request body for POST /sessions.
 * SessionID is the caller-minted session identifier. When set, the bridge
 * uses it as the session's primary key and rejects collisions with 409.
 * When empty, the bridge mints one (br_<nanos>). Caller-mints lets workers
 * (autoworker, scheduler, etc.) hold a synchronous handle for kanban links
 * before the create round-trip returns; interactive callers may leave it
 * empty and consume the server-minted value. Recommended caller format:
 * ULID. See MIGRATION-session-identity.md.
 * Source is an origin tag set by the caller identifying what created this
 * session (e.g. "scheduler", "autoworker"). Interactive UI callers leave it
 * empty. The server persists it on the session and may auto-assign a folder
 * based on the value (see LLMBRIDGE_SOURCE_FOLDERS).
 * SessionType categorizes the session (interactive / autonomous / system).
 * Currently optional for backward compatibility; will be required once all
 * callers are updated. See MIGRATION-session-identity.md.
 */
export interface CreateSessionRequest {
  harness: Harness;
  session_id?: string;
  instance_id?: string;
  display_name?: string;
  agent_id?: string;
  spawner_id?: string;
  auto_start?: boolean;
  source?: string;
  session_type?: SessionType;
  harness_config?: Record<string, unknown>; // opaque harness-specific config, merged into start params
  /**
   * Mode selects events (default) or pty I/O. Pty requires the harness
   * to advertise SupportsPTY()==true; otherwise the server returns
   * 400 with error code "pty_unsupported".
   */
  mode?: SessionMode;
}
/**
 * SendMessageRequest is the request body for POST /sessions/{id}/send.
 * Either Message (plain text) or Blocks (canonical content-block array for
 * multimodal input — text, images, documents) carries the user's turn.
 * The two are mutually exclusive: setting both is rejected at the server
 * boundary so harnesses never have to disambiguate downstream.
 * ClientRequestID is a caller-minted identifier for this turn. The bridge
 * stamps it on every event it emits for the turn so producers can correlate
 * server-side state with their own outbound request. Optional — callers that
 * don't need correlation can leave it empty.
 */
export interface SendMessageRequest {
  message: string;
  blocks?: ContentBlock[];
  client_request_id?: string;
}
/**
 * ForkSessionRequest is the request body for POST /sessions/{id}/fork.
 */
export interface ForkSessionRequest {
  display_name?: string;
  session_type?: SessionType;
}
/**
 * CompactSessionRequest is the request body for POST /sessions/{id}/compact.
 */
export interface CompactSessionRequest {
  summary?: string;
}
/**
 * ConfigSessionRequest is the request body for POST /sessions/{id}/config.
 */
export interface ConfigSessionRequest {
  model?: string;
  effort?: string;
  disabled_tools?: string[];
  max_budget?: number /* float64 */;
}
/**
 * CreateInstanceRequest is the request body for POST /instances.
 * MachineID is required — instances always belong to a machine. Use
 * CreateMachineRequest first (or have a runner enroll) to obtain one.
 */
export interface CreateInstanceRequest {
  harness_type: string;
  name: string;
  machine_id: string;
  working_dir?: string;
  max_concurrent_sessions?: number /* int */;
}
/**
 * CreateMachineRequest is the request body for POST /machines.
 */
export interface CreateMachineRequest {
  name: string;
  emoji?: string;
  hostname?: string;
  os?: string;
  arch?: string;
  transport: Transport;
  ssh_user?: string;
  ssh_key_path?: string;
  ssh_port?: number /* int */;
  default_working_dir?: string;
  notes?: string;
}
/**
 * UpdateMachineRequest patches a machine. Empty fields are left unchanged.
 */
export interface UpdateMachineRequest {
  name?: string;
  emoji?: string;
  hostname?: string;
  os?: string;
  arch?: string;
  transport?: Transport;
  ssh_user?: string;
  ssh_key_path?: string;
  ssh_port?: number /* int */;
  default_working_dir?: string;
  notes?: string;
}
/**
 * MintEnrollmentRequest creates a one-time enrollment passphrase for a runner.
 * TTLSeconds defaults to 900 (15 min) on the server when zero.
 */
export interface MintEnrollmentRequest {
  ttl_seconds?: number /* int */;
}
/**
 * MintEnrollmentResponse carries the freshly-minted passphrase. The server
 * stores only its hash; this is the only chance to capture the plaintext.
 */
export interface MintEnrollmentResponse {
  passphrase: string;
  expires_at: string;
}
/**
 * EnrollRunnerRequest is the request body for POST /api/runner/enroll.
 * The passphrase is a single-use credential; the rest is the runner's
 * self-report of its environment, used to populate the auto-created
 * Machine row.
 */
export interface EnrollRunnerRequest {
  passphrase: string;
  machine_name?: string; // defaults to hostname
  hostname: string;
  os: string;
  arch: string;
  user?: string;
  working_dir?: string;
  available_harnesses?: HarnessAvailable[];
  runner_version?: string;
}
/**
 * EnrollRunnerResponse returns the durable per-machine token the runner
 * will present on subsequent WS connections. Save it locally; the server
 * stores only its hash.
 */
export interface EnrollRunnerResponse {
  machine_id: string;
  machine_name: string;
  runner_token: string;
  instance_ids: string[]; // default instances auto-created for this machine
}
/**
 * BindCredentialRequest is the request body for POST /instances/{id}/credentials.
 */
export interface BindCredentialRequest {
  credential_id: string;
  priority: number /* int */;
}
/**
 * RenameSessionRequest is the request body for POST /sessions/{id}/rename.
 */
export interface RenameSessionRequest {
  display_name: string;
}
/**
 * SourceFolderMapping is one row of the runtime source→folder map.
 * Default=true means the value comes from the env-var defaults
 * (LLMBRIDGE_SOURCE_FOLDERS) with no runtime override; Default=false means
 * the row originates from the source_folders table. UpdatedAt is zero for
 * env defaults.
 */
export interface SourceFolderMapping {
  source: string;
  folder_name: string;
  default: boolean;
  updated_at?: string;
}
/**
 * PutSourceFolderRequest is the request body for PUT /source-folders/{source}.
 * FolderName must reference an existing folder (validated server-side).
 * ApplyToExisting=true rebuckets prior sessions whose folder is empty or
 * matches the previous effective folder for this source; manual moves are
 * preserved.
 */
export interface PutSourceFolderRequest {
  folder_name: string;
  apply_to_existing?: boolean;
}
/**
 * SourceFolderApplyResult is the response payload for PUT/DELETE when
 * ApplyToExisting was requested. Updated is the row count from the rebucket
 * UPDATE.
 */
export interface SourceFolderApplyResult {
  mapping: SourceFolderMapping;
  updated: number /* int64 */;
}

//////////
// source: session.go

/**
 * Session represents an agent session across any harness.
 */
export interface Session {
  id: string;
  harness: Harness;
  state: SessionState;
  agent?: string;
  orchestrator?: string;
  model?: string;
  created_at: string;
  last_active: string;
  ended_at?: string;
  context_tokens?: number /* int */;
  context_limit?: number /* int */;
  total_usage: TokenUsage;
  total_cost?: Cost;
  turn_count: number /* int */;
  /**
   * Config is harness-specific session configuration (json.RawMessage).
   */
  config?: Record<string, unknown>;
  tasks?: SessionTask[];
  active_request?: string;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * SessionTask tracks a task within a session.
 */
export interface SessionTask {
  content: string;
  status: string;
  active_form?: string;
}
/**
 * StoredSession represents a session discovered on disk from a harness's
 * native storage (e.g. ~/.claude/projects/ or ~/.codex/sessions/).
 * These are sessions that exist outside the llm-bridge-server's own store.
 */
export interface StoredSession {
  /**
   * HarnessSessionID is the harness-native session id (Claude session UUID,
   * Codex thread_id, Hermes dashboard id, ...). Required. Bridge-server
   * dedupes discovery results on this field, so it MUST be the harness's
   * own id — never a bridge-server-minted bridge_id.
   */
  harness_session_id: string;
  /**
   * BridgeSessionID is bridge-server's stable session id, set when the
   * harness has already been adopted by bridge-server (i.e. state.db
   * recorded a `bridge_session_id` for this harness session). Empty for
   * cold-imported sessions that have never been bound to bridge-server.
   * When non-empty, bridge-server treats the session as already known and
   * skips it during discovery.
   */
  bridge_session_id?: string;
  harness: Harness;
  project?: string; // project directory or context
  prompt?: string; // initial prompt snippet
  created_at: string;
  updated_at: string; // file modification time
  path: string; // on-disk path to session file
  turn_count?: number /* int */; // approximate number of turns
  /**
   * Source is a structural origin tag the harness adapter sets when the
   * on-disk layout classifies a session (e.g. CC stores Task()-spawned
   * subagents under <session>/subagents/agent-*.jsonl, so the claudecode
   * adapter tags those Source="subagent"). Empty when the adapter has no
   * structural signal — bridge-server then falls back to prompt-prefix
   * inference. Mirrors ManagedSession.Source so it flows straight into
   * LLMBRIDGE_SOURCE_FOLDERS bucketing.
   */
  source?: string;
}

//////////
// source: session_meta.go

/**
 * FolderList is the ordered list of user-defined folder names for organizing
 * sessions in the sidebar. Folder assignment per session lives on
 * [ManagedSession.FolderName] so it travels with the session row.
 */
export interface FolderList {
  folder_order: string[];
}
/**
 * CreateFolderRequest is the body for POST /folders.
 */
export interface CreateFolderRequest {
  name: string;
}
/**
 * RenameFolderRequest is the body for PUT /folders/{name}.
 */
export interface RenameFolderRequest {
  new_name: string;
}
/**
 * SetSessionFolderRequest is the body for PUT /sessions/{id}/folder.
 * An empty Folder string clears the assignment (un-files the session).
 */
export interface SetSessionFolderRequest {
  folder: string;
}
/**
 * FileInactiveRequest is the body for POST /admin/file-inactive.
 * Sessions whose updated_at is older than InactiveDays and which are not
 * already filed move into Folder. Folder is auto-created if it doesn't
 * exist in the registry.
 */
export interface FileInactiveRequest {
  inactive_days: number /* int */;
  folder: string;
}
/**
 * FileInactiveResponse reports the outcome of a file-inactive sweep.
 */
export interface FileInactiveResponse {
  moved: number /* int */;
  folder: string;
  ids?: string[];
}
/**
 * ArchiveOldRequest is the body for POST /admin/archive-old.
 * Every session (in any folder other than the Archive folder) whose
 * updated_at is older than InactiveDays and which is not currently
 * running moves into the Archive folder. The Archive folder is
 * auto-created if it doesn't exist in the registry.
 */
export interface ArchiveOldRequest {
  inactive_days: number /* int */;
}
/**
 * ArchiveOldResponse reports the outcome of an archive-old sweep.
 */
export interface ArchiveOldResponse {
  moved: number /* int */;
  ids?: string[];
}
/**
 * MarkSessionDoneRequest is the body for POST /sessions/{id}/mark-done.
 * Done=true atomically (a) emits an EventSessionState{State: completed}
 * through the central derivation pipeline so the row state and SSE feed
 * agree, and (b) moves the session into the canonical Archive folder.
 * Done=false reverses both: state goes to idle, folder is cleared.
 * If new events flow in after the manual mark, derivation overwrites the
 * state (e.g. a new tool_call flips back to tool_running). That's
 * intentional — the session re-engaging visibly says "no longer done".
 */
export interface MarkSessionDoneRequest {
  done: boolean;
}

//////////
// source: stream.go

/**
 * StreamEventType identifies the kind of streaming event.
 */
export type StreamEventType = string;
export const StreamEventStart: StreamEventType = "stream_start";
export const StreamEventContentBlockStart: StreamEventType = "content_block_start";
export const StreamEventContentBlockDelta: StreamEventType = "content_block_delta";
export const StreamEventContentBlockStop: StreamEventType = "content_block_stop";
export const StreamEventMessageDelta: StreamEventType = "message_delta";
export const StreamEventMessageStop: StreamEventType = "message_stop";
export const StreamEventPing: StreamEventType = "ping";
export const StreamEventError: StreamEventType = "error";
/**
 * StreamEvent is the unified streaming event type.
 * Follows Anthropic's granular model (most expressive) and synthesizes
 * block-level events for providers that don't have them (OpenAI, Gemini).
 */
export interface StreamEvent {
  type: StreamEventType;
  start?: StreamStart;
  block_start?: BlockStart;
  block_delta?: BlockDelta;
  block_stop?: BlockStop;
  msg_delta?: MessageDelta;
  error?: StreamError;
  /**
   * Raw is the complete original provider JSON for this stream event.
   */
  raw?: Record<string, unknown>;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * StreamStart carries initial message metadata.
 */
export interface StreamStart {
  id: string;
  model: string;
  provider: Provider;
  usage: TokenUsage;
}
/**
 * BlockStart signals a new content block beginning.
 */
export interface BlockStart {
  index: number /* int */;
  block: ContentBlock;
}
/**
 * DeltaType identifies the kind of streaming delta.
 */
export type DeltaType = string;
export const DeltaText: DeltaType = "text_delta";
export const DeltaInputJSON: DeltaType = "input_json_delta";
export const DeltaThinking: DeltaType = "thinking_delta";
export const DeltaSignature: DeltaType = "signature_delta";
export const DeltaAudio: DeltaType = "audio_delta";
/**
 * BlockDelta carries incremental content for a block.
 */
export interface BlockDelta {
  index: number /* int */;
  type: DeltaType;
  text?: string;
  partial_json?: string;
  thinking?: string;
  signature?: string;
  audio_data?: string;
}
/**
 * BlockStop signals a content block has finished.
 */
export interface BlockStop {
  index: number /* int */;
}
/**
 * MessageDelta carries end-of-message metadata.
 */
export interface MessageDelta {
  stop_reason: StopReason;
  native_stop_reason?: string;
  stop_sequence?: string;
  usage: TokenUsage;
}
/**
 * StreamError represents an error during streaming.
 */
export interface StreamError {
  type: string;
  message: string;
  code?: string;
  retryable?: boolean;
  retry_after_ms?: number /* int */;
  status_code?: number /* int */;
}

//////////
// source: tool.go

/**
 * ToolDef defines a tool the model can call.
 */
export interface ToolDef {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
  strict?: boolean;
  cache_control?: CacheControl;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * ToolChoiceMode determines how the model selects tools.
 */
export type ToolChoiceMode = string;
export const ToolChoiceAuto: ToolChoiceMode = "auto";
export const ToolChoiceAny: ToolChoiceMode = "any";
export const ToolChoiceNone: ToolChoiceMode = "none";
export const ToolChoiceRequired: ToolChoiceMode = "required";
export const ToolChoiceSpecific: ToolChoiceMode = "specific";
/**
 * ToolChoice controls model tool selection behavior.
 */
export interface ToolChoice {
  mode: ToolChoiceMode;
  name?: string;
  disable_parallel?: boolean;
}

//////////
// source: usage.go

/**
 * TokenUsage tracks token consumption across all providers.
 */
export interface TokenUsage {
  input_tokens: number /* int */;
  output_tokens: number /* int */;
  total_tokens: number /* int */;
  cache_read_tokens?: number /* int */;
  cache_write_tokens?: number /* int */;
  reasoning_tokens?: number /* int */;
  context_tokens?: number /* int */;
  context_limit?: number /* int */;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * Cost tracks monetary cost of a request.
 */
export interface Cost {
  total_usd: number /* float64 */;
  input_usd?: number /* float64 */;
  output_usd?: number /* float64 */;
  is_byok?: boolean;
  upstream_cost?: number /* float64 */;
}

//////////
// source: validate.go

/**
 * ValidationError contains one or more validation failures.
 */
export interface ValidationError {
  Failures: ValidationFailure[];
}
/**
 * ValidationFailure describes a single validation issue.
 */
export interface ValidationFailure {
  Path: string;
  Code: string;
  Message: string;
}
/**
 * Validation error codes — conversation/response.
 */
export const ErrEmptyField = "empty_field";
/**
 * Validation error codes — conversation/response.
 */
export const ErrInvalidRole = "invalid_role";
/**
 * Validation error codes — conversation/response.
 */
export const ErrInvalidBlockType = "invalid_block_type";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMultipleBlocksSet = "multiple_blocks_set";
/**
 * Validation error codes — conversation/response.
 */
export const ErrNoBlockSet = "no_block_set";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMissingToolID = "missing_tool_id";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMissingToolName = "missing_tool_name";
/**
 * Validation error codes — conversation/response.
 */
export const ErrOrphanedToolResult = "orphaned_tool_result";
/**
 * Validation error codes — conversation/response.
 */
export const ErrAlternationViolation = "alternation_violation";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMissingModel = "missing_model";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMissingProvider = "missing_provider";
/**
 * Validation error codes — conversation/response.
 */
export const ErrInvalidStopReason = "invalid_stop_reason";
/**
 * Validation error codes — conversation/response.
 */
export const ErrThinkingNoSignature = "thinking_no_signature";
/**
 * Validation error codes — conversation/response.
 */
export const ErrOpaqueDataModified = "opaque_data_modified";
/**
 * Validation error codes — event/session.
 */
export const ErrMissingSessionID = "missing_session_id";
/**
 * Validation error codes — event/session.
 */
export const ErrMissingBridgeSessionID = "missing_bridge_session_id";
/**
 * Validation error codes — event/session.
 */
export const ErrMissingHarness = "missing_harness";
/**
 * Validation error codes — event/session.
 */
export const ErrInvalidEventType = "invalid_event_type";
/**
 * Validation error codes — event/session.
 */
export const ErrNoEventPayload = "no_event_payload";
/**
 * Validation error codes — event/session.
 */
export const ErrMultiplePayloads = "multiple_payloads";
/**
 * Validation error codes — event/session.
 */
export const ErrInvalidSessionState = "invalid_session_state";
/**
 * Validation error codes — event/session.
 */
export const ErrMissingTimestamp = "missing_timestamp";
