// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/llm-bridge/msg @ f7b290ea0ca610b4e5c56b67693d278db3722efe
// Source of truth: Go types in msg/*.go
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: config.go

/**
 * GenerationConfig holds provider-agnostic generation parameters.
 */
export interface GenerationConfig {
  max_tokens?: number /* int */;
  temperature?: number /* float64 */;
  top_p?: number /* float64 */;
  top_k?: number /* int */;
  stop_sequences?: string[];
  stream?: boolean;
  response_format?: ResponseFormat;
}
/**
 * ResponseFormat specifies structured output requirements.
 */
export interface ResponseFormat {
  type: string;
  json_schema?: Record<string, unknown>;
  strict?: boolean;
}
/**
 * AnthropicConfig holds Anthropic-specific request parameters.
 */
export interface AnthropicConfig {
  thinking_budget?: number /* int */;
  thinking_display?: string;
  effort?: string;
  container_id?: string;
  service_tier?: string;
  inference_geo?: string;
  assistant_prefill?: ContentBlock[];
  metadata?: { [key: string]: string};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * OpenAIConfig holds OpenAI-specific request parameters.
 */
export interface OpenAIConfig {
  prediction?: string;
  logprobs?: boolean;
  top_logprobs?: number /* int */;
  n?: number /* int */;
  frequency_penalty?: number /* float64 */;
  presence_penalty?: number /* float64 */;
  seed?: number /* int */;
  stream_include_usage?: boolean;
  store?: boolean;
  previous_response_id?: string;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * GeminiConfig holds Gemini-specific request parameters.
 */
export interface GeminiConfig {
  safety_settings?: SafetySetting[];
  cached_content?: string;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * OpenRouterConfig holds OpenRouter-specific request parameters.
 */
export interface OpenRouterConfig {
  models?: string[];
  route?: string;
  provider_prefs?: OpenRouterProviderPrefs;
  plugins?: OpenRouterPlugin[];
  debug?: boolean;
  top_a?: number /* float64 */;
  min_p?: number /* float64 */;
  repetition_penalty?: number /* float64 */;
  prediction?: string;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * OpenRouterProviderPrefs controls model routing preferences.
 */
export interface OpenRouterProviderPrefs {
  order?: string[];
  allow_fallbacks?: boolean;
  require_parameters?: boolean;
}
/**
 * OpenRouterPlugin is an OpenRouter plugin configuration.
 */
export interface OpenRouterPlugin {
  id: string;
  enabled: boolean;
}

//////////
// source: content.go

/**
 * BlockType identifies the kind of content block.
 */
export type BlockType = string;
export const BlockText: BlockType = "text";
export const BlockImage: BlockType = "image";
export const BlockAudio: BlockType = "audio";
export const BlockVideo: BlockType = "video";
export const BlockDocument: BlockType = "document";
export const BlockToolUse: BlockType = "tool_use";
export const BlockToolResult: BlockType = "tool_result";
export const BlockThinking: BlockType = "thinking";
export const BlockRedactedThinking: BlockType = "redacted_thinking";
export const BlockCodeExec: BlockType = "code_exec";
export const BlockCodeExecResult: BlockType = "code_exec_result";
export const BlockServerToolResult: BlockType = "server_tool_result";
export const BlockRefusal: BlockType = "refusal";
/**
 * ContentBlock is a discriminated union of all possible content block types.
 * Exactly one of the typed fields will be non-nil, matching Type.
 */
export interface ContentBlock {
  type: BlockType;
  text_block?: TextBlock;
  image_block?: ImageBlock;
  audio_block?: AudioBlock;
  video_block?: VideoBlock;
  document_block?: DocumentBlock;
  tool_use_block?: ToolUseBlock;
  tool_result_block?: ToolResultBlock;
  thinking_block?: ThinkingBlock;
  redacted_thinking_block?: RedactedThinkingBlock;
  code_exec_block?: CodeExecBlock;
  code_exec_result_block?: CodeExecResultBlock;
  server_tool_result_block?: ServerToolResultBlock;
  refusal_block?: RefusalBlock;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * TextBlock represents plain text content.
 */
export interface TextBlock {
  text: string;
  citations?: Citation[];
  cache_control?: CacheControl;
}
/**
 * Citation references a source document by character position.
 */
export interface Citation {
  type: string;
  cited_text: string;
  document_index: number /* int */;
  start_char_index?: number /* int */;
  end_char_index?: number /* int */;
  start_page?: number /* int */;
  end_page?: number /* int */;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * CacheControl is Anthropic's per-block cache hint.
 */
export interface CacheControl {
  type: string; // "ephemeral"
  ttl?: string;
}
/**
 * MediaSourceKind identifies how media data is provided.
 */
export type MediaSourceKind = string;
export const MediaBase64: MediaSourceKind = "base64";
export const MediaURL: MediaSourceKind = "url";
export const MediaFileID: MediaSourceKind = "file_id";
/**
 * MediaSource unifies how media (images, audio, video, docs) are referenced.
 */
export interface MediaSource {
  kind: MediaSourceKind;
  media_type: string;
  data: string;
  detail?: string;
  format?: string;
  filename?: string;
}
/**
 * ImageBlock represents an image in any encoding.
 */
export interface ImageBlock {
  source: MediaSource;
  cache_control?: CacheControl;
}
/**
 * AudioBlock represents audio content.
 */
export interface AudioBlock {
  source: MediaSource;
  cache_control?: CacheControl;
}
/**
 * VideoBlock represents video content.
 */
export interface VideoBlock {
  source: MediaSource;
  cache_control?: CacheControl;
}
/**
 * DocumentBlock represents a document (PDF, plain text, etc.).
 */
export interface DocumentBlock {
  source: MediaSource;
  title?: string;
  citations_enabled?: boolean;
  cache_control?: CacheControl;
}
/**
 * ToolUseBlock represents the model requesting a tool call.
 */
export interface ToolUseBlock {
  id: string;
  original_id: string;
  name: string;
  input: Record<string, unknown>;
  cache_control?: CacheControl;
}
/**
 * ToolResultBlock represents the result of a tool call.
 */
export interface ToolResultBlock {
  tool_use_id: string;
  original_tool_use_id: string;
  content?: ContentBlock[];
  is_error?: boolean;
  source_role?: string;
  tool_name?: string;
}
/**
 * ThinkingBlock represents model reasoning/thinking traces.
 */
export interface ThinkingBlock {
  text: string;
  signature?: string;
  budget_tokens?: number /* int */;
}
/**
 * RedactedThinkingBlock represents thinking content redacted by the provider.
 */
export interface RedactedThinkingBlock {
  data: string;
}
/**
 * CodeExecBlock represents a code execution request.
 */
export interface CodeExecBlock {
  language: string;
  code: string;
}
/**
 * CodeExecResultBlock represents the output of code execution.
 */
export interface CodeExecResultBlock {
  outcome: string;
  output: string;
}
/**
 * ServerToolResultBlock represents results from provider-hosted tools.
 */
export interface ServerToolResultBlock {
  tool_type: string;
  content: Record<string, unknown>;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * RefusalBlock represents the model explicitly refusing a request.
 */
export interface RefusalBlock {
  text: string;
}

//////////
// source: event.go

/**
 * Event is the unified harness event type.
 * All harness-specific events are normalized into this structure.
 */
export interface Event {
  type: EventType;
  harness: Harness;
  session_id: string;
  bridge_id?: string;
  client_id?: string;
  completion_id?: string;
  /**
   * ClientRequestID is the caller-minted per-turn identifier forwarded from
   * SendMessageRequest. Stamped on every event the bridge emits for that
   * turn so producers can correlate server-side state with their outbound
   * request. Empty for events outside a turn (session_state, system, etc.)
   * and for turns where the caller didn't supply one.
   */
  client_request_id?: string;
  /**
   * MessageID is the canonical bridge-server-assigned identifier for the
   * chat message this event belongs to (ULID, "msg_…"). Stable across SSE
   * reconnects and harness restarts. Empty for bookkeeping events
   * (system, session_state, session_info, harness_id_set) that do not
   * belong to a user-visible message bubble.
   */
  message_id?: string;
  /**
   * HarnessMessageID is the harness-native identifier for the same logical
   * message (e.g. Claude Code's msg_…). Used for reconciliation when a
   * harness resumes and re-emits prior messages. Empty when the harness
   * does not surface one.
   */
  harness_message_id?: string;
  timestamp: string;
  /**
   * Content — at most one of these will be populated based on Type.
   */
  result?: ResultEvent;
  stream?: HarnessStream;
  tool_call?: ToolCallEvent;
  tool_result?: ToolResultEvent;
  thinking?: ThinkingEvent;
  plan?: PlanEvent;
  system?: SystemEvent;
  approval?: ApprovalEvent;
  error?: ErrorEvent;
  state?: StateEvent;
  info?: SessionInfo;
  /**
   * Raw preserves the original event JSON from the harness for pass-through.
   */
  raw?: Record<string, unknown>;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * ResultEvent is a completed harness run.
 */
export interface ResultEvent {
  text: string;
  message?: Message;
  is_error?: boolean;
  structured_output?: Record<string, unknown>;
  usage: TokenUsage;
  cost?: Cost;
  duration_ms?: number /* int64 */;
  duration_api_ms?: number /* int64 */;
  num_turns?: number /* int */;
  api_calls?: number /* int */;
  model?: string;
  api_call_usages?: TokenUsage[];
  tool_events?: ToolSummary[];
}
/**
 * ToolSummary records a tool invocation within a completed run.
 */
export interface ToolSummary {
  tool: string;
  input?: string;
  output?: string;
  error?: string;
}
/**
 * HarnessStream is a streaming text/content event from the harness.
 * Named HarnessStream to avoid collision with StreamEvent (API-level streaming).
 */
export interface HarnessStream {
  delta?: BlockDelta;
  message_id?: string;
  hidden?: boolean;
}
/**
 * ToolCallEvent is a tool being invoked.
 */
export interface ToolCallEvent {
  tool_id: string;
  name: string;
  input: Record<string, unknown>;
}
/**
 * ToolResultEvent is the output of a tool invocation.
 */
export interface ToolResultEvent {
  tool_id: string;
  name: string;
  output: string;
  is_error?: boolean;
}
/**
 * ThinkingEvent is a thinking/reasoning event.
 */
export interface ThinkingEvent {
  text: string;
  subtype?: string; // "", "summary"
}
/**
 * PlanEvent is a structured task-planning event (distinct from thinking).
 */
export interface PlanEvent {
  text: string;
}
/**
 * SystemEvent is a system-level notification.
 */
export interface SystemEvent {
  subtype: string;
  message?: string;
  attempt?: number /* int */;
  max_retries?: number /* int */;
  retry_delay_ms?: number /* int */;
  error_status?: number /* int */;
  error_type?: string;
}
/**
 * ApprovalEvent represents a permission request or response.
 */
export interface ApprovalEvent {
  action: string;
  status: string;
  tool_name?: string;
  detail?: string;
  command?: string;
  path?: string;
  patch?: string;
  permissions?: string[];
  prompt?: string;
}
/**
 * ErrorEvent represents a harness-level error.
 */
export interface ErrorEvent {
  code: string;
  message: string;
  retryable?: boolean;
  status_code?: number /* int */;
}
/**
 * StateEvent represents a session state change.
 */
export interface StateEvent {
  state: SessionState;
  previous?: SessionState;
  reason?: string;
}
/**
 * SessionInfo describes what the harness knows about its session at start:
 * the system prompt it was configured with, the working directory, and the
 * tools / slash commands / sub-agents / MCP servers the underlying agent
 * reports as available. Emitted by the harness as an EventSessionInfo after
 * the agent's initial handshake, and persisted on ManagedSession so it can
 * be retrieved via GET /sessions/{id} without replaying events.
 */
export interface SessionInfo {
  system_prompt?: string;
  append_system_prompt?: string;
  working_dir?: string;
  model?: string;
  permission_mode?: string;
  tools?: ToolInfo[];
  slash_commands?: string[];
  agents?: string[];
  skills?: string[];
  mcp_servers?: MCPServerInfo[];
}
/**
 * ToolInfo names a tool the agent has available. Description is optional —
 * the harness only reports what the underlying agent exposes; the UI may
 * enrich with its own descriptions.
 */
export interface ToolInfo {
  name: string;
  description?: string;
}
/**
 * MCPServerInfo describes an MCP server connection reported by the agent.
 */
export interface MCPServerInfo {
  name: string;
  status?: string;
}

//////////
// source: instance.go

/**
 * Transport specifies how to connect to a harness instance.
 */
export type Transport = string;
export const TransportLocal: Transport = "local"; // local subprocess
export const TransportSSH: Transport = "ssh"; // SSH to remote machine
/**
 * Instance represents a deployed harness on a specific machine.
 * A harness type (claudecode, codex) is a template; an instance is a running deployment.
 */
export interface Instance {
  id: string;
  harness_type: Harness;
  name: string; // human label: "laptop-cc", "ci-runner-1"
  host: string; // "localhost", "dev.internal", "ci-01.example.com"
  transport: Transport;
  ssh_user?: string;
  ssh_key_path?: string;
  ssh_port?: number /* int */; // default 22
  working_dir?: string;
  max_concurrent_sessions: number /* int */;
  enabled: boolean;
  created_at: string;
  updated_at: string;
}
/**
 * InstanceCredential binds a credential to a harness instance with priority.
 */
export interface InstanceCredential {
  instance_id: string;
  credential_id: string;
  priority: number /* int */; // 0 = primary, 1+ = fallbacks
  enabled: boolean;
}
/**
 * InstanceStatus aggregates runtime status for an instance.
 */
export interface InstanceStatus {
  instance: Instance;
  active_sessions: number /* int */;
  credentials: InstanceCredential[];
  reachable: boolean; // SSH connectivity check
  last_checked: string;
}

//////////
// source: message.go

/**
 * Conversation represents a complete request to an LLM API.
 */
export interface Conversation {
  id?: string;
  model: string;
  provider: Provider;
  /**
   * System prompt — always a slice of content blocks, never a bare string.
   */
  system?: ContentBlock[];
  messages: Message[];
  tools?: ToolDef[];
  tool_choice?: ToolChoice;
  config: GenerationConfig;
  provider_config?: Record<string, unknown>; // AnthropicConfig | OpenAIConfig | GeminiConfig | OpenRouterConfig
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   * Keys are namespaced by bridge (e.g. "anthropic:beta_feature").
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * Message is a single turn in a conversation.
 */
export interface Message {
  id?: string;
  role: Role;
  /**
   * Content is always a slice of typed blocks.
   */
  content: ContentBlock[];
  /**
   * Name is an optional participant identifier (OpenAI supports this).
   */
  name?: string;
  /**
   * NativeRole preserves the original provider role for lossless round-trip.
   */
  native_role?: NativeRole;
  /**
   * SourcePattern records how this message was originally structured for round-trip.
   */
  source_pattern?: string;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}

//////////
// source: provider.go

/**
 * Provider identifies which LLM API produced or will consume a message.
 */
export type Provider = string;
export const ProviderAnthropic: Provider = "anthropic";
export const ProviderOpenAI: Provider = "openai";
export const ProviderGemini: Provider = "gemini";
export const ProviderOpenRouter: Provider = "openrouter";
/**
 * Role is the normalized message role across all providers.
 */
export type Role = string;
export const RoleSystem: Role = "system";
export const RoleUser: Role = "user";
export const RoleAssistant: Role = "assistant";
export const RoleTool: Role = "tool";
/**
 * NativeRole maps to provider-specific role strings.
 */
export interface NativeRole {
  provider: Provider;
  value: string; // e.g. "model" for Gemini, "developer" for OpenAI o-series
}
/**
 * StopReason is the normalized reason a completion ended.
 */
export type StopReason = string;
export const StopEnd: StopReason = "end";
export const StopMaxTokens: StopReason = "max_tokens";
export const StopToolUse: StopReason = "tool_use";
export const StopStopSequence: StopReason = "stop_sequence";
export const StopSafety: StopReason = "safety";
export const StopContentFilter: StopReason = "content_filter";
export const StopRecitation: StopReason = "recitation";
export const StopError: StopReason = "error";
/**
 * Harness identifies which agent harness produced an event.
 */
export type Harness = string;
export const HarnessClaudeCode: Harness = "claude_code";
export const HarnessCodex: Harness = "codex";
export const HarnessOpenClaw: Harness = "openclaw";
export const HarnessInber: Harness = "inber";
export const HarnessHermes: Harness = "hermes";
export const HarnessAider: Harness = "aider";
export const HarnessGoose: Harness = "goose";
export const HarnessAutohand: Harness = "autohand";
export const HarnessJig: Harness = "jig";
export const HarnessDexto: Harness = "dexto";
export const HarnessCommander: Harness = "commander";
export const HarnessNanoClaw: Harness = "nanoclaw";
export const HarnessCline: Harness = "cline";
export const HarnessRooCode: Harness = "roo_code";
export const HarnessKiloCode: Harness = "kilo_code";
export const HarnessOpenCode: Harness = "opencode";
/**
 * EventType classifies a harness event.
 */
export type EventType = string;
export const EventResult: EventType = "result";
export const EventStream: EventType = "stream";
export const EventToolCall: EventType = "tool_call";
export const EventToolResult: EventType = "tool_result";
export const EventThinking: EventType = "thinking";
export const EventSystem: EventType = "system";
export const EventApproval: EventType = "approval";
export const EventError: EventType = "error";
export const EventSessionState: EventType = "session_state";
export const EventPlan: EventType = "plan";
export const EventSessionInfo: EventType = "session_info";
export const EventUserMessage: EventType = "user_message";
/**
 * SessionState represents the current state of a harness session.
 */
export type SessionState = string;
export const SessionIdle: SessionState = "idle";
export const SessionRunning: SessionState = "running";
export const SessionCompleted: SessionState = "completed";
export const SessionError: SessionState = "error";
export const SessionAborted: SessionState = "aborted";
export const SessionWaitingApproval: SessionState = "waiting_on_approval";

//////////
// source: response.go

/**
 * CompletionResponse is the unified response from any LLM API.
 */
export interface CompletionResponse {
  id: string;
  model: string;
  provider: Provider;
  message: Message;
  stop_reason: StopReason;
  native_stop_reason: string;
  stop_sequence?: string;
  usage: TokenUsage;
  cost?: Cost;
  /**
   * Gemini: per-response safety ratings.
   */
  safety_ratings?: SafetyRating[];
  /**
   * OpenAI: server-side configuration fingerprint.
   */
  system_fingerprint?: string;
  /**
   * OpenAI: logprobs for the response tokens.
   */
  logprobs?: LogProbs;
  /**
   * OpenAI: multiple choices when n > 1.
   */
  additional_choices?: CompletionChoice[];
  /**
   * Raw is the complete original provider JSON response.
   * Preserved for debugging and detecting data missed by the bridge.
   */
  raw?: Record<string, unknown>;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   * Keys are namespaced by bridge (e.g. "anthropic:beta_feature", "openai:service_tier").
   * This allows bridges to pass through new features before the spec adds official support.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * CompletionChoice represents one of potentially multiple completions (OpenAI n > 1).
 */
export interface CompletionChoice {
  index: number /* int */;
  message: Message;
  stop_reason: StopReason;
  native_stop_reason: string;
}
/**
 * SafetyRating is a Gemini per-category safety assessment.
 */
export interface SafetyRating {
  category: string;
  probability: string;
  blocked?: boolean;
}
/**
 * SafetySetting configures Gemini safety thresholds.
 */
export interface SafetySetting {
  category: string;
  threshold: string;
}
/**
 * LogProbs contains OpenAI token log probability data.
 */
export interface LogProbs {
  content?: TokenLogProb[];
}
/**
 * TokenLogProb is the log probability for a single token.
 */
export interface TokenLogProb {
  token: string;
  logprob: number /* float64 */;
  bytes?: number /* int */[];
  top_logprobs?: TopLogProb[];
}
/**
 * TopLogProb is one of the top-k alternative tokens.
 */
export interface TopLogProb {
  token: string;
  logprob: number /* float64 */;
  bytes?: number /* int */[];
}

//////////
// source: server.go

/**
 * ManagedSession is a session as tracked by llm-bridge-server.
 * This is the server's lightweight session management entity, distinct from
 * [Session] which models rich agent-level state (usage, tasks, context).
 * Three IDs track a session through its lifecycle:
 *   - BridgeID: server-generated primary key, stable from creation.
 *   - HarnessID: the canonical harness session ID (e.g. CC UUID). Empty until
 *     the harness reports it on first event.
 *   - ClientID: the frontend's correlation key (fe_*). Set at creation,
 *     never changes. Used by the frontend to relate the response back to its
 *     optimistic UI entry.
 */
export interface ManagedSession {
  bridge_id: string;
  harness_id?: string;
  client_id?: string;
  display_name: string;
  harness: Harness;
  instance_id?: string;
  state: string;
  pid?: number /* int */;
  agent_id?: string;
  spawner_id?: string;
  parent_id?: string;
  harness_config?: Record<string, unknown>; // opaque harness-specific config
  info?: SessionInfo; // latest session info reported by the harness
  folder_name?: string; // user-assigned sidebar folder; empty = unfiled
  created_at: string;
  updated_at: string;
}
/**
 * HarnessInfo describes a registered harness type and its capabilities.
 */
export interface HarnessInfo {
  name: string;
  label: string;
  emoji: string;
  image?: string;
  available: boolean;
  binary?: string;
  capabilities: string[];
  supported_providers?: string[];
}
/**
 * Credential represents an API credential as exposed by the server.
 * Sensitive fields are masked (api_key_masked, token_masked).
 */
export interface Credential {
  id: string;
  provider: string;
  label: string;
  auth_type: string;
  api_key_masked?: string;
  token_masked?: string;
  priority: number /* int */;
  enabled: boolean;
  expires_at: number /* int64 */;
  error_count?: number /* int */;
  last_error?: string;
}
/**
 * HarnessDefaults stores per-harness configuration defaults.
 */
export interface HarnessDefaults {
  model?: string;
  effort?: string;
  max_budget?: number /* float64 */;
  disabled_tools?: string[];
}
/**
 * BridgePrefs stores user preferences for the bridge dashboard.
 */
export interface BridgePrefs {
  last_harness?: string;
  last_instance_id?: string;
  last_session?: { [key: string]: string};
  last_instance?: { [key: string]: string};
  defaults?: { [key: string]: HarnessDefaults};
}
/**
 * MaterializedMessage is a flattened message returned by the messages API.
 * Assembled from raw events by log-store: stream deltas are concatenated,
 * tool calls are collected, and the final ResultEvent becomes Meta.
 */
export interface MaterializedMessage {
  id?: string; // canonical bridge MessageID
  harness_message_id?: string; // harness-native id, if known
  role: string;
  content: string;
  thinking?: string;
  tools?: MaterializedTool[];
  meta?: ResultEvent;
  events?: Record<string, unknown>[];
  timestamp: string;
  done: boolean;
}
/**
 * MaterializedTool records a tool invocation within a materialized message.
 */
export interface MaterializedTool {
  tool_id: string;
  tool: string;
  input?: Record<string, unknown>;
  output?: string;
  error?: boolean;
}
/**
 * HealthResponse is the server's health check response.
 */
export interface HealthResponse {
  status: string;
  harnesses: HarnessInfo[];
  sessions: SessionCounts;
}
/**
 * SessionCounts is a breakdown of active sessions by state.
 */
export interface SessionCounts {
  running: number /* int */;
  idle: number /* int */;
  completed: number /* int */;
}
/**
 * ConformanceFeature is a capability that a harness may or may not support.
 */
export type ConformanceFeature = string;
/**
 * ConformanceTestResult records the outcome of a single feature test.
 */
export interface ConformanceTestResult {
  feature: ConformanceFeature;
  passed: boolean;
  skipped?: boolean;
  error?: string;
  duration?: string;
}
/**
 * ConformanceHarnessResult records all test results for a single harness.
 */
export interface ConformanceHarnessResult {
  harness: string;
  binary: string;
  tested_at: string;
  results: ConformanceTestResult[];
  summary: ConformanceSummary;
}
/**
 * ConformanceSummary counts test outcomes.
 */
export interface ConformanceSummary {
  total: number /* int */;
  passed: number /* int */;
  failed: number /* int */;
  skipped: number /* int */;
}
/**
 * ConformanceMatrix holds conformance results for all tested harnesses.
 */
export interface ConformanceMatrix {
  generated_at: string;
  harnesses: ConformanceHarnessResult[];
}
/**
 * CreateSessionRequest is the request body for POST /sessions.
 */
export interface CreateSessionRequest {
  harness: Harness;
  instance_id?: string;
  display_name?: string;
  agent_id?: string;
  spawner_id?: string;
  auto_start?: boolean;
  client_id?: string;
  harness_config?: Record<string, unknown>; // opaque harness-specific config, merged into start params
}
/**
 * SendMessageRequest is the request body for POST /sessions/{id}/send.
 * ClientRequestID is a caller-minted identifier for this turn. The bridge
 * stamps it on every event it emits for the turn so producers can correlate
 * server-side state with their own outbound request. Optional — callers that
 * don't need correlation can leave it empty.
 */
export interface SendMessageRequest {
  message: string;
  client_request_id?: string;
}
/**
 * ForkSessionRequest is the request body for POST /sessions/{id}/fork.
 */
export interface ForkSessionRequest {
  display_name?: string;
  client_id?: string;
}
/**
 * CompactSessionRequest is the request body for POST /sessions/{id}/compact.
 */
export interface CompactSessionRequest {
  summary?: string;
}
/**
 * ConfigSessionRequest is the request body for POST /sessions/{id}/config.
 */
export interface ConfigSessionRequest {
  model?: string;
  effort?: string;
  disabled_tools?: string[];
  max_budget?: number /* float64 */;
}
/**
 * CreateInstanceRequest is the request body for POST /instances.
 */
export interface CreateInstanceRequest {
  harness_type: string;
  name: string;
  host?: string;
  transport?: Transport;
  ssh_user?: string;
  ssh_key_path?: string;
  ssh_port?: number /* int */;
  working_dir?: string;
  max_concurrent_sessions?: number /* int */;
}
/**
 * BindCredentialRequest is the request body for POST /instances/{id}/credentials.
 */
export interface BindCredentialRequest {
  credential_id: string;
  priority: number /* int */;
}
/**
 * RenameSessionRequest is the request body for POST /sessions/{id}/rename.
 */
export interface RenameSessionRequest {
  display_name: string;
}

//////////
// source: session.go

/**
 * Session represents an agent session across any harness.
 */
export interface Session {
  id: string;
  harness: Harness;
  state: SessionState;
  agent?: string;
  orchestrator?: string;
  model?: string;
  created_at: string;
  last_active: string;
  ended_at?: string;
  context_tokens?: number /* int */;
  context_limit?: number /* int */;
  total_usage: TokenUsage;
  total_cost?: Cost;
  turn_count: number /* int */;
  /**
   * Config is harness-specific session configuration (json.RawMessage).
   */
  config?: Record<string, unknown>;
  tasks?: SessionTask[];
  active_request?: string;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * SessionTask tracks a task within a session.
 */
export interface SessionTask {
  content: string;
  status: string;
  active_form?: string;
}
/**
 * StoredSession represents a session discovered on disk from a harness's
 * native storage (e.g. ~/.claude/projects/ or ~/.codex/sessions/).
 * These are sessions that exist outside the llm-bridge-server's own store.
 */
export interface StoredSession {
  id: string;
  harness: Harness;
  project?: string; // project directory or context
  prompt?: string; // initial prompt snippet
  created_at: string;
  updated_at: string; // file modification time
  path: string; // on-disk path to session file
  turn_count?: number /* int */; // approximate number of turns
}

//////////
// source: session_meta.go

/**
 * FolderList is the ordered list of user-defined folder names for organizing
 * sessions in the sidebar. Folder assignment per session lives on
 * [ManagedSession.FolderName] so it travels with the session row.
 */
export interface FolderList {
  folder_order: string[];
}
/**
 * CreateFolderRequest is the body for POST /folders.
 */
export interface CreateFolderRequest {
  name: string;
}
/**
 * RenameFolderRequest is the body for PUT /folders/{name}.
 */
export interface RenameFolderRequest {
  new_name: string;
}
/**
 * SetSessionFolderRequest is the body for PUT /sessions/{id}/folder.
 * An empty Folder string clears the assignment (un-files the session).
 */
export interface SetSessionFolderRequest {
  folder: string;
}

//////////
// source: stream.go

/**
 * StreamEventType identifies the kind of streaming event.
 */
export type StreamEventType = string;
export const StreamEventStart: StreamEventType = "stream_start";
export const StreamEventContentBlockStart: StreamEventType = "content_block_start";
export const StreamEventContentBlockDelta: StreamEventType = "content_block_delta";
export const StreamEventContentBlockStop: StreamEventType = "content_block_stop";
export const StreamEventMessageDelta: StreamEventType = "message_delta";
export const StreamEventMessageStop: StreamEventType = "message_stop";
export const StreamEventPing: StreamEventType = "ping";
export const StreamEventError: StreamEventType = "error";
/**
 * StreamEvent is the unified streaming event type.
 * Follows Anthropic's granular model (most expressive) and synthesizes
 * block-level events for providers that don't have them (OpenAI, Gemini).
 */
export interface StreamEvent {
  type: StreamEventType;
  start?: StreamStart;
  block_start?: BlockStart;
  block_delta?: BlockDelta;
  block_stop?: BlockStop;
  msg_delta?: MessageDelta;
  error?: StreamError;
  /**
   * Raw is the complete original provider JSON for this stream event.
   */
  raw?: Record<string, unknown>;
  /**
   * Extensions holds bridge-specific typed data not yet in the canonical schema.
   */
  extensions?: { [key: string]: Record<string, unknown>};
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * StreamStart carries initial message metadata.
 */
export interface StreamStart {
  id: string;
  model: string;
  provider: Provider;
  usage: TokenUsage;
}
/**
 * BlockStart signals a new content block beginning.
 */
export interface BlockStart {
  index: number /* int */;
  block: ContentBlock;
}
/**
 * DeltaType identifies the kind of streaming delta.
 */
export type DeltaType = string;
export const DeltaText: DeltaType = "text_delta";
export const DeltaInputJSON: DeltaType = "input_json_delta";
export const DeltaThinking: DeltaType = "thinking_delta";
export const DeltaSignature: DeltaType = "signature_delta";
export const DeltaAudio: DeltaType = "audio_delta";
/**
 * BlockDelta carries incremental content for a block.
 */
export interface BlockDelta {
  index: number /* int */;
  type: DeltaType;
  text?: string;
  partial_json?: string;
  thinking?: string;
  signature?: string;
  audio_data?: string;
}
/**
 * BlockStop signals a content block has finished.
 */
export interface BlockStop {
  index: number /* int */;
}
/**
 * MessageDelta carries end-of-message metadata.
 */
export interface MessageDelta {
  stop_reason: StopReason;
  native_stop_reason?: string;
  stop_sequence?: string;
  usage: TokenUsage;
}
/**
 * StreamError represents an error during streaming.
 */
export interface StreamError {
  type: string;
  message: string;
  code?: string;
  retryable?: boolean;
  retry_after_ms?: number /* int */;
  status_code?: number /* int */;
}

//////////
// source: tool.go

/**
 * ToolDef defines a tool the model can call.
 */
export interface ToolDef {
  name: string;
  description: string;
  input_schema: Record<string, unknown>;
  strict?: boolean;
  cache_control?: CacheControl;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * ToolChoiceMode determines how the model selects tools.
 */
export type ToolChoiceMode = string;
export const ToolChoiceAuto: ToolChoiceMode = "auto";
export const ToolChoiceAny: ToolChoiceMode = "any";
export const ToolChoiceNone: ToolChoiceMode = "none";
export const ToolChoiceRequired: ToolChoiceMode = "required";
export const ToolChoiceSpecific: ToolChoiceMode = "specific";
/**
 * ToolChoice controls model tool selection behavior.
 */
export interface ToolChoice {
  mode: ToolChoiceMode;
  name?: string;
  disable_parallel?: boolean;
}

//////////
// source: usage.go

/**
 * TokenUsage tracks token consumption across all providers.
 */
export interface TokenUsage {
  input_tokens: number /* int */;
  output_tokens: number /* int */;
  total_tokens: number /* int */;
  cache_read_tokens?: number /* int */;
  cache_write_tokens?: number /* int */;
  reasoning_tokens?: number /* int */;
  context_tokens?: number /* int */;
  context_limit?: number /* int */;
  _overflow?: { [key: string]: Record<string, unknown>};
}
/**
 * Cost tracks monetary cost of a request.
 */
export interface Cost {
  total_usd: number /* float64 */;
  input_usd?: number /* float64 */;
  output_usd?: number /* float64 */;
  is_byok?: boolean;
  upstream_cost?: number /* float64 */;
}

//////////
// source: validate.go

/**
 * ValidationError contains one or more validation failures.
 */
export interface ValidationError {
  Failures: ValidationFailure[];
}
/**
 * ValidationFailure describes a single validation issue.
 */
export interface ValidationFailure {
  Path: string;
  Code: string;
  Message: string;
}
/**
 * Validation error codes — conversation/response.
 */
export const ErrEmptyField = "empty_field";
/**
 * Validation error codes — conversation/response.
 */
export const ErrInvalidRole = "invalid_role";
/**
 * Validation error codes — conversation/response.
 */
export const ErrInvalidBlockType = "invalid_block_type";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMultipleBlocksSet = "multiple_blocks_set";
/**
 * Validation error codes — conversation/response.
 */
export const ErrNoBlockSet = "no_block_set";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMissingToolID = "missing_tool_id";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMissingToolName = "missing_tool_name";
/**
 * Validation error codes — conversation/response.
 */
export const ErrOrphanedToolResult = "orphaned_tool_result";
/**
 * Validation error codes — conversation/response.
 */
export const ErrAlternationViolation = "alternation_violation";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMissingModel = "missing_model";
/**
 * Validation error codes — conversation/response.
 */
export const ErrMissingProvider = "missing_provider";
/**
 * Validation error codes — conversation/response.
 */
export const ErrInvalidStopReason = "invalid_stop_reason";
/**
 * Validation error codes — conversation/response.
 */
export const ErrThinkingNoSignature = "thinking_no_signature";
/**
 * Validation error codes — conversation/response.
 */
export const ErrOpaqueDataModified = "opaque_data_modified";
/**
 * Validation error codes — event/session.
 */
export const ErrMissingSessionID = "missing_session_id";
/**
 * Validation error codes — event/session.
 */
export const ErrMissingHarness = "missing_harness";
/**
 * Validation error codes — event/session.
 */
export const ErrInvalidEventType = "invalid_event_type";
/**
 * Validation error codes — event/session.
 */
export const ErrNoEventPayload = "no_event_payload";
/**
 * Validation error codes — event/session.
 */
export const ErrMultiplePayloads = "multiple_payloads";
/**
 * Validation error codes — event/session.
 */
export const ErrInvalidSessionState = "invalid_session_state";
/**
 * Validation error codes — event/session.
 */
export const ErrMissingTimestamp = "missing_timestamp";
