# AUTO-GENERATED — DO NOT EDIT THIS FILE.
#
# Generated from github.com/kayushkin/llm-bridge/msg @ 59ca93bb0b354522de7852f547cd2456b97aa028-dirty
# Source of truth: Go types in msg/*.go
# To regenerate: ./generate-py.sh
#
# Any manual changes will be overwritten on the next generation run.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# ────────────────────────────────────────
# source: config.go


@dataclass(kw_only=True)
class GenerationConfig:
    """GenerationConfig holds provider-agnostic generation parameters."""
    max_tokens: int | None = None
    temperature: float | None = None
    top_p: float | None = None
    top_k: int | None = None
    stop_sequences: list[str] | None = None
    stream: bool | None = None
    response_format: ResponseFormat | None = None


@dataclass(kw_only=True)
class ResponseFormat:
    """ResponseFormat specifies structured output requirements."""
    type: str
    json_schema: dict[str, Any] | None = None
    strict: bool | None = None


@dataclass(kw_only=True)
class AnthropicConfig:
    """AnthropicConfig holds Anthropic-specific request parameters."""
    thinking_budget: int | None = None
    thinking_display: str | None = None
    effort: str | None = None
    container_id: str | None = None
    service_tier: str | None = None
    inference_geo: str | None = None
    assistant_prefill: list[ContentBlock] | None = None
    metadata: dict[str, str] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class OpenAIConfig:
    """OpenAIConfig holds OpenAI-specific request parameters."""
    prediction: str | None = None
    logprobs: bool | None = None
    top_logprobs: int | None = None
    n: int | None = None
    frequency_penalty: float | None = None
    presence_penalty: float | None = None
    seed: int | None = None
    stream_include_usage: bool | None = None
    store: bool | None = None
    previous_response_id: str | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class GeminiConfig:
    """GeminiConfig holds Gemini-specific request parameters."""
    safety_settings: list[SafetySetting] | None = None
    cached_content: str | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class OpenRouterConfig:
    """OpenRouterConfig holds OpenRouter-specific request parameters."""
    models: list[str] | None = None
    route: str | None = None
    provider_prefs: OpenRouterProviderPrefs | None = None
    plugins: list[OpenRouterPlugin] | None = None
    debug: bool | None = None
    top_a: float | None = None
    min_p: float | None = None
    repetition_penalty: float | None = None
    prediction: str | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class OpenRouterProviderPrefs:
    """OpenRouterProviderPrefs controls model routing preferences."""
    order: list[str] | None = None
    allow_fallbacks: bool | None = None
    require_parameters: bool | None = None


@dataclass(kw_only=True)
class OpenRouterPlugin:
    """OpenRouterPlugin is an OpenRouter plugin configuration."""
    id: str
    enabled: bool


# ────────────────────────────────────────
# source: content.go

# BlockType identifies the kind of content block.
BlockType = str

BlockText: BlockType = "text"
BlockImage: BlockType = "image"
BlockAudio: BlockType = "audio"
BlockVideo: BlockType = "video"
BlockDocument: BlockType = "document"
BlockToolUse: BlockType = "tool_use"
BlockToolResult: BlockType = "tool_result"
BlockThinking: BlockType = "thinking"
BlockRedactedThinking: BlockType = "redacted_thinking"
BlockCodeExec: BlockType = "code_exec"
BlockCodeExecResult: BlockType = "code_exec_result"
BlockServerToolResult: BlockType = "server_tool_result"
BlockRefusal: BlockType = "refusal"


@dataclass(kw_only=True)
class ContentBlock:
    """ContentBlock is a discriminated union of all possible content block types. Exactly one of the typed fields will be non-nil, matching Type."""
    type: BlockType
    text_block: TextBlock | None = None
    image_block: ImageBlock | None = None
    audio_block: AudioBlock | None = None
    video_block: VideoBlock | None = None
    document_block: DocumentBlock | None = None
    tool_use_block: ToolUseBlock | None = None
    tool_result_block: ToolResultBlock | None = None
    thinking_block: ThinkingBlock | None = None
    redacted_thinking_block: RedactedThinkingBlock | None = None
    code_exec_block: CodeExecBlock | None = None
    code_exec_result_block: CodeExecResultBlock | None = None
    server_tool_result_block: ServerToolResultBlock | None = None
    refusal_block: RefusalBlock | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class TextBlock:
    """TextBlock represents plain text content."""
    text: str
    citations: list[Citation] | None = None
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class Citation:
    """Citation references a source document by character position."""
    type: str
    cited_text: str
    document_index: int
    start_char_index: int | None = None
    end_char_index: int | None = None
    start_page: int | None = None
    end_page: int | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class CacheControl:
    """CacheControl is Anthropic's per-block cache hint."""
    type: str  # "ephemeral"
    ttl: str | None = None

# MediaSourceKind identifies how media data is provided.
MediaSourceKind = str

MediaBase64: MediaSourceKind = "base64"
MediaURL: MediaSourceKind = "url"
MediaFileID: MediaSourceKind = "file_id"


@dataclass(kw_only=True)
class MediaSource:
    """MediaSource unifies how media (images, audio, video, docs) are referenced."""
    kind: MediaSourceKind
    media_type: str
    data: str
    detail: str | None = None
    format: str | None = None
    filename: str | None = None


@dataclass(kw_only=True)
class ImageBlock:
    """ImageBlock represents an image in any encoding."""
    source: MediaSource
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class AudioBlock:
    """AudioBlock represents audio content."""
    source: MediaSource
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class VideoBlock:
    """VideoBlock represents video content."""
    source: MediaSource
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class DocumentBlock:
    """DocumentBlock represents a document (PDF, plain text, etc.)."""
    source: MediaSource
    title: str | None = None
    citations_enabled: bool | None = None
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class ToolUseBlock:
    """ToolUseBlock represents the model requesting a tool call."""
    id: str
    original_id: str
    name: str
    input: dict[str, Any]
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class ToolResultBlock:
    """ToolResultBlock represents the result of a tool call."""
    tool_use_id: str
    original_tool_use_id: str
    content: list[ContentBlock] | None = None
    is_error: bool | None = None
    source_role: str | None = None
    tool_name: str | None = None


@dataclass(kw_only=True)
class ThinkingBlock:
    """ThinkingBlock represents model reasoning/thinking traces."""
    text: str
    signature: str | None = None
    budget_tokens: int | None = None


@dataclass(kw_only=True)
class RedactedThinkingBlock:
    """RedactedThinkingBlock represents thinking content redacted by the provider."""
    data: str


@dataclass(kw_only=True)
class CodeExecBlock:
    """CodeExecBlock represents a code execution request."""
    language: str
    code: str


@dataclass(kw_only=True)
class CodeExecResultBlock:
    """CodeExecResultBlock represents the output of code execution."""
    outcome: str
    output: str


@dataclass(kw_only=True)
class ServerToolResultBlock:
    """ServerToolResultBlock represents results from provider-hosted tools."""
    tool_type: str
    content: dict[str, Any]
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class RefusalBlock:
    """RefusalBlock represents the model explicitly refusing a request."""
    text: str


# ────────────────────────────────────────
# source: event.go


@dataclass(kw_only=True)
class Event:
    """Event is the unified harness event type. All harness-specific events are normalized into this structure."""
    type: EventType
    harness: Harness
    bridge_session_id: str
    harness_session_id: str | None = None
    completion_id: str | None = None
    client_request_id: str | None = None
    turn_id: str | None = None
    message_id: str | None = None
    harness_message_id: str | None = None
    timestamp: str
    result: ResultEvent | None = None
    stream: HarnessStream | None = None
    block: BlockEvent | None = None
    tool_call: ToolCallEvent | None = None
    tool_result: ToolResultEvent | None = None
    thinking: ThinkingEvent | None = None
    plan: PlanEvent | None = None
    system: SystemEvent | None = None
    approval: ApprovalEvent | None = None
    error: ErrorEvent | None = None
    state: StateEvent | None = None
    info: SessionInfo | None = None
    hook: HookEvent | None = None
    agent_state: AgentStateEvent | None = None
    usage_total: UsageTotalEvent | None = None
    turn_complete: TurnCompleteEvent | None = None
    derived_from: list[str] | None = None
    raw: dict[str, Any] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class ResultEvent:
    """ResultEvent is a completed harness run. Also reused as the payload for EventUserMessage events to record what the user sent: Text holds plain-text input; Blocks holds multimodal input (text/image/document/audio/video). The two are mutually exclusive at the request boundary."""
    text: str
    blocks: list[ContentBlock] | None = None
    message: Message | None = None
    is_error: bool | None = None
    structured_output: dict[str, Any] | None = None
    usage: TokenUsage
    cost: Cost | None = None
    duration_ms: int | None = None
    duration_api_ms: int | None = None
    num_turns: int | None = None
    api_calls: int | None = None
    model: str | None = None
    api_call_usages: list[TokenUsage] | None = None
    tool_events: list[ToolSummary] | None = None


@dataclass(kw_only=True)
class ToolSummary:
    """ToolSummary records a tool invocation within a completed run."""
    tool: str
    input: str | None = None
    output: str | None = None
    error: str | None = None


@dataclass(kw_only=True)
class HarnessStream:
    """HarnessStream is a streaming text/content event from the harness. Named HarnessStream to avoid collision with StreamEvent (API-level streaming).  EventStream carries true incremental deltas (token chunks, partial JSON, thinking summary chunks). Whole finished content blocks ride EventBlock instead — see BlockEvent. A harness emits EventStream only when it has granular streaming enabled (e.g. Claude Code with --include-partial-messages)."""
    delta: BlockDelta | None = None
    message_id: str | None = None
    hidden: bool | None = None


@dataclass(kw_only=True)
class BlockEvent:
    """BlockEvent carries one finished content block from a harness assistant message. Distinct from EventStream: EventBlock is one-shot per completed block (the block has stopped accumulating); EventStream is incremental.  Block is the discriminated-union content carrier from msg/content.go, covering text, thinking, tool_use, tool_result, images, etc. — every content variant a harness might surface.  MessageID is the harness-native id of the assistant message containing this block (e.g. Claude Code's msg_…), used for grouping multiple blocks from the same model turn into one chat bubble. Index matches the block's position in the original message's content array."""
    index: int
    message_id: str | None = None
    block: ContentBlock | None = None


@dataclass(kw_only=True)
class ToolCallEvent:
    """ToolCallEvent is a tool being invoked.  MessageID is the harness-native id of the assistant bubble that contained this tool_use block (e.g. Claude Code's msg_…). It's the same id the surrounding text/thinking events carry on HarnessStream.MessageID — so the bridge server can group tool_call events into their bubble without parsing the raw harness payload."""
    tool_id: str
    name: str
    input: dict[str, Any]
    message_id: str | None = None


@dataclass(kw_only=True)
class ToolResultEvent:
    """ToolResultEvent is the output of a tool invocation.  MessageID mirrors ToolCallEvent.MessageID — the harness-native id of the bubble that contained the tool_result block."""
    tool_id: str
    name: str
    output: str
    is_error: bool | None = None
    message_id: str | None = None


@dataclass(kw_only=True)
class ThinkingEvent:
    """ThinkingEvent is a thinking/reasoning event."""
    text: str
    subtype: str | None = None  # "", "summary"


@dataclass(kw_only=True)
class PlanEvent:
    """PlanEvent is a structured task-planning event (distinct from thinking)."""
    text: str


@dataclass(kw_only=True)
class SystemEvent:
    """SystemEvent is a system-level notification.  ToolUseID / TaskID / Description / LastToolName are populated for the "task_progress" subtype (Claude Code's narration of an in-flight tool call). ToolUseID is the harness-native tool id (e.g. Anthropic's toolu_…) — the bridge server uses it to resolve the event back to the containing message bubble and stamp MessageID/HarnessMessageID."""
    subtype: str
    message: str | None = None
    attempt: int | None = None
    max_retries: int | None = None
    retry_delay_ms: int | None = None
    error_status: int | None = None
    error_type: str | None = None
    tool_use_id: str | None = None
    task_id: str | None = None
    description: str | None = None
    last_tool_name: str | None = None


@dataclass(kw_only=True)
class ApprovalEvent:
    """ApprovalEvent represents a permission request or response.  Deprecated: emit HookEvent with Source="permission_prompt" and the awaiting_resolution / completed phase pair instead. Kept this cycle so existing harnesses can transition; consumers should treat both as the same signal. Will be removed in a future release."""
    action: str
    status: str
    tool_name: str | None = None
    detail: str | None = None
    command: str | None = None
    path: str | None = None
    patch: str | None = None
    permissions: list[str] | None = None
    prompt: str | None = None


@dataclass(kw_only=True)
class ErrorEvent:
    """ErrorEvent represents a harness-level error."""
    code: str
    message: str
    retryable: bool | None = None
    status_code: int | None = None


@dataclass(kw_only=True)
class StateEvent:
    """StateEvent represents a session state change."""
    state: SessionState
    previous: SessionState | None = None
    reason: str | None = None

# AgentState was a coarser UI-projection of session lifecycle (4 values).  Deprecated: SessionState now carries the full UI vocabulary (13 values) that AgentState was projecting toward. Consumers should switch on SessionState directly via StateEvent. Type kept during the migration window so existing references compile; will be removed once llm-bridge-server stops emitting EventAgentState and consumers migrate.
AgentState = str

AgentStateIdle: AgentState = "idle"
AgentStateAwaitingInput: AgentState = "awaiting_input"
AgentStateToolRunning: AgentState = "tool_running"
AgentStateError: AgentState = "error"


@dataclass(kw_only=True)
class AgentStateEvent:
    """AgentStateEvent is the body for EventAgentState.  Deprecated: see AgentState above."""
    state: AgentState
    previous: AgentState | None = None
    reason: str | None = None  # free-form, e.g. "tool=Bash", "approval_required"


@dataclass(kw_only=True)
class UsageTotalEvent:
    """UsageTotalEvent is the body for EventUsageTotal. Carries the running session totals, not a delta — emitted once after every ResultEvent fan-out. ContextTokens / ContextLimit on Usage are last-value-wins (state, not consumption); all other TokenUsage fields are summed."""
    usage: TokenUsage  # cumulative across every result event in this session
    cost: Cost | None = None  # sum where reported; nil until any priced turn lands
    turns: int  # how many completed turns contributed


@dataclass(kw_only=True)
class TurnCompleteEvent:
    """TurnCompleteEvent is the body for EventTurnComplete. Emitted once per turn, immediately after the terminating ResultEvent (or ErrorEvent for error-terminated turns) is fanned out. TurnID matches the originating user_message's turn_id."""
    turn_id: str  # matches the originating user_message's turn_id
    final_message: str | None = None  # last assistant text in the turn (from ResultEvent.Text)
    tool_calls: list[ToolSummary] | None = None  # every tool_call/tool_result pair seen in this turn
    usage_delta: TokenUsage  # this turn's contribution
    cost: Cost | None = None
    duration_ms: int  # wall-clock from user_message → result
    is_error: bool | None = None
    error_message: str | None = None


@dataclass(kw_only=True)
class SessionInfo:
    """SessionInfo describes what the harness knows about its session at start: the system prompt it was configured with, the working directory, and the tools / slash commands / sub-agents / MCP servers the underlying agent reports as available. Emitted by the harness as an EventSessionInfo after the agent's initial handshake, and persisted on ManagedSession so it can be retrieved via GET /sessions/{id} without replaying events."""
    system_prompt: str | None = None
    append_system_prompt: str | None = None
    working_dir: str | None = None
    model: str | None = None
    permission_mode: str | None = None
    tools: list[ToolInfo] | None = None
    slash_commands: list[str] | None = None
    agents: list[str] | None = None
    skills: list[str] | None = None
    mcp_servers: list[MCPServerInfo] | None = None


@dataclass(kw_only=True)
class ToolInfo:
    """ToolInfo names a tool the agent has available. Description is optional — the harness only reports what the underlying agent exposes; the UI may enrich with its own descriptions."""
    name: str
    description: str | None = None


@dataclass(kw_only=True)
class MCPServerInfo:
    """MCPServerInfo describes an MCP server connection reported by the agent."""
    name: str
    status: str | None = None


@dataclass(kw_only=True)
class HookEvent:
    """HookEvent records a harness hook lifecycle event.  Three sources produce HookEvents, discriminated by Source / HookID:   1. Harness-native observation (Source empty or "hook", HookID empty) — the     underlying harness emits its own hook lifecycle notifications (e.g.     Claude Code with --include-hook-events) and the bridge translates them.     The bridge has no control over these hooks.  2. Bridge-registered invocation (Source empty or "hook", HookID set) — a     hook registered with the hook-store fires via the harness's native     mechanism, which shells out to the bridge server's /hooks/exec/{id}     endpoint.  3. Permission-prompt invocation (Source="permission_prompt") — the harness     wired a permission-prompt callback (e.g. Claude Code's     --permission-prompt-tool MCP server) and is consulting the bridge for a     tool-use decision. Functionally a synthetic PreToolUse hook whose     resolver is human (or shell or auto) per the bridge's settings.  Input and Output are raw JSON, passed through in the underlying harness's native dialect (e.g. Claude Code's stdin/stdout hook protocol). Layers are transparent: no translation into a neutral schema."""
    event: str
    matcher: str | None = None
    tool_name: str | None = None
    hook_id: str | None = None
    source: str | None = None
    phase: str
    request_id: str | None = None
    input: dict[str, Any] | None = None
    output: dict[str, Any] | None = None
    decision: str | None = None
    resolution: HookResolution | None = None
    exit_code: int | None = None
    duration_ms: int | None = None
    error: str | None = None


@dataclass(kw_only=True)
class HookResolution:
    """HookResolution captures the decision that closed an awaiting_resolution hook."""
    behavior: str
    updated_input: dict[str, Any] | None = None
    message: str | None = None
    resolved_by: str | None = None


# ────────────────────────────────────────
# source: hook.go

# HookScope identifies the resolution layer a hook lives on.  Hooks compose: a session inherits every enabled hook whose scope matches, across all three layers. When two scopes register a hook with the same (harness, event, matcher), the most specific scope wins: session > instance > global.
HookScope = str

HookScopeGlobal: HookScope = "global"
HookScopeInstance: HookScope = "instance"
HookScopeSession: HookScope = "session"


@dataclass(kw_only=True)
class Hook:
    """Hook is a registered hook handler. Each Hook describes one (event, matcher) pair on one harness, bound to a local shell command that runs when the underlying harness fires the event. The command receives the harness's native hook stdin and returns the harness's native hook stdout — the bridge does not translate either direction.  For Claude Code: the command is wired into a synthesized settings JSON (passed to `claude` via --settings) when a session spawns. When CC invokes the hook, it shells out to the bridge server's /hooks/exec/{id} endpoint, which executes Command with stdin/stdout pass-through."""
    id: str  # ULID
    harness: Harness  # claudecode, codex, ...
    event: str  # harness-native event name (PreToolUse, etc.)
    matcher: str | None = None
    command: str
    scope_kind: HookScope
    scope_id: str | None = None
    enabled: bool
    created_at: str
    updated_at: str


# ────────────────────────────────────────
# source: instance.go

# Transport specifies how a harness subprocess is reached on its host.
Transport = str

TransportLocal: Transport = "local"
TransportSSH: Transport = "ssh"
TransportRunner: Transport = "runner"


@dataclass(kw_only=True)
class Machine:
    """Machine represents a host where harness subprocesses can run. One row per physical/virtual host. Multiple instances may share a machine (e.g. claude_code and codex on the same laptop). Created either explicitly (local/ssh) or auto-created when an llm-bridge-runner enrolls."""
    id: str  # m_<id>
    name: str  # unique, human label: "linode", "wsl-claude"
    emoji: str | None = None  # optional UI accent: 🏠 🖥 ☁ etc.
    hostname: str | None = None  # network address (Tailscale name, IP, …); empty for runner
    os: str | None = None  # GOOS reported by runner, or set on create
    arch: str | None = None  # GOARCH
    transport: Transport
    ssh_user: str | None = None
    ssh_key_path: str | None = None
    ssh_port: int | None = None  # default 22
    default_working_dir: str | None = None
    user: str | None = None  # runner-side OS user (display only)
    notes: str | None = None
    last_seen_at: str | None = None
    created_at: str
    updated_at: str


@dataclass(kw_only=True)
class Instance:
    """Instance represents a configured harness deployment on a machine. The Machine pointer is populated by API responses for client convenience; internal storage code reads from the machines table directly."""
    id: str
    harness_type: Harness
    name: str
    machine_id: str
    working_dir: str | None = None  # overrides Machine.DefaultWorkingDir for this instance
    max_concurrent_sessions: int
    enabled: bool
    created_at: str
    updated_at: str
    machine: Machine | None = None


@dataclass(kw_only=True)
class InstanceCredential:
    """InstanceCredential binds a credential to a harness instance with priority."""
    instance_id: str
    credential_id: str
    priority: int  # 0 = primary, 1+ = fallbacks
    enabled: bool


@dataclass(kw_only=True)
class InstanceStatus:
    """InstanceStatus aggregates runtime status for an instance."""
    instance: Instance
    active_sessions: int
    credentials: list[InstanceCredential]
    reachable: bool  # SSH/runner connectivity check
    last_checked: str


@dataclass(kw_only=True)
class RunnerEnrollment:
    """RunnerEnrollment is a one-time-use token that lets a runner self-register a Machine without prior server-side configuration. Minted by an admin (CLI or API), redeemed by the runner via POST /api/runner/enroll."""
    id: str  # enr_<id>
    expires_at: str
    used_at: str | None = None  # zero if unused
    consumed_machine_id: str | None = None  # set when redeemed
    created_at: str


# ────────────────────────────────────────
# source: message.go


@dataclass(kw_only=True)
class Conversation:
    """Conversation represents a complete request to an LLM API."""
    id: str | None = None
    model: str
    provider: Provider
    system: list[ContentBlock] | None = None
    messages: list[Message]
    tools: list[ToolDef] | None = None
    tool_choice: ToolChoice | None = None
    config: GenerationConfig
    provider_config: dict[str, Any] | None = None  # AnthropicConfig | OpenAIConfig | GeminiConfig | OpenRouterConfig
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class Message:
    """Message is a single turn in a conversation."""
    id: str | None = None
    role: Role
    content: list[ContentBlock]
    name: str | None = None
    native_role: NativeRole | None = None
    source_pattern: str | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


# ────────────────────────────────────────
# source: provider.go

# Provider identifies which LLM API produced or will consume a message.
Provider = str

ProviderAnthropic: Provider = "anthropic"
ProviderOpenAI: Provider = "openai"
ProviderGemini: Provider = "gemini"
ProviderOpenRouter: Provider = "openrouter"

# Role is the normalized message role across all providers.
Role = str

RoleSystem: Role = "system"
RoleUser: Role = "user"
RoleAssistant: Role = "assistant"
RoleTool: Role = "tool"


@dataclass(kw_only=True)
class NativeRole:
    """NativeRole maps to provider-specific role strings."""
    provider: Provider
    value: str  # e.g. "model" for Gemini, "developer" for OpenAI o-series

# StopReason is the normalized reason a completion ended.
StopReason = str

StopEnd: StopReason = "end"
StopMaxTokens: StopReason = "max_tokens"
StopToolUse: StopReason = "tool_use"
StopStopSequence: StopReason = "stop_sequence"
StopSafety: StopReason = "safety"
StopContentFilter: StopReason = "content_filter"
StopRecitation: StopReason = "recitation"
StopError: StopReason = "error"

# Harness identifies which agent harness produced an event.
Harness = str

HarnessClaudeCode: Harness = "claude_code"
HarnessCodex: Harness = "codex"
HarnessOpenClaw: Harness = "openclaw"
HarnessInber: Harness = "inber"
HarnessHermes: Harness = "hermes"
HarnessAider: Harness = "aider"
HarnessGoose: Harness = "goose"
HarnessAutohand: Harness = "autohand"
HarnessJig: Harness = "jig"
HarnessDexto: Harness = "dexto"
HarnessCommander: Harness = "commander"
HarnessNanoClaw: Harness = "nanoclaw"
HarnessCline: Harness = "cline"
HarnessRooCode: Harness = "roo_code"
HarnessKiloCode: Harness = "kilo_code"
HarnessOpenCode: Harness = "opencode"
HarnessForgecode: Harness = "forgecode"
HarnessGemini: Harness = "gemini"

# EventType classifies a harness event.
EventType = str

EventResult: EventType = "result"
EventStream: EventType = "stream"
EventBlock: EventType = "block"
EventToolCall: EventType = "tool_call"
EventToolResult: EventType = "tool_result"
EventThinking: EventType = "thinking"
EventSystem: EventType = "system"
EventApproval: EventType = "approval"
EventError: EventType = "error"
EventSessionState: EventType = "session_state"
EventPlan: EventType = "plan"
EventSessionInfo: EventType = "session_info"
EventUserMessage: EventType = "user_message"
EventHook: EventType = "hook"
EventAgentState: EventType = "agent_state"
EventUsageTotal: EventType = "usage_total"
EventTurnComplete: EventType = "turn_complete"

# SessionState represents the current state of an llm-bridge-managed session. Authoritative values are derived centrally by llm-bridge-server from the raw event stream plus server-only context (pause/abort calls, permission-store hook state, subprocess lifecycle, provider rate-limit signals). Harnesses no longer emit SessionState directly — they emit raw actions (tool_call, tool_result, block, hook, error) and the server computes the state.
SessionState = str

SessionStarting: SessionState = "starting"
SessionModelGenerating: SessionState = "model_generating"
SessionToolRunning: SessionState = "tool_running"
SessionCompacting: SessionState = "compacting"
SessionAwaitingPermission: SessionState = "awaiting_permission"
SessionAwaitingUser: SessionState = "awaiting_user"
SessionRateLimited: SessionState = "rate_limited"
SessionPaused: SessionState = "paused"
SessionIdle: SessionState = "idle"
SessionCompleted: SessionState = "completed"
SessionError: SessionState = "error"
SessionAborted: SessionState = "aborted"
SessionDisconnected: SessionState = "disconnected"
SessionRunning: SessionState = "running"
SessionWaitingApproval: SessionState = "waiting_on_approval"


# ────────────────────────────────────────
# source: response.go


@dataclass(kw_only=True)
class CompletionResponse:
    """CompletionResponse is the unified response from any LLM API."""
    id: str
    model: str
    provider: Provider
    message: Message
    stop_reason: StopReason
    native_stop_reason: str
    stop_sequence: str | None = None
    usage: TokenUsage
    cost: Cost | None = None
    safety_ratings: list[SafetyRating] | None = None
    system_fingerprint: str | None = None
    logprobs: LogProbs | None = None
    additional_choices: list[CompletionChoice] | None = None
    raw: dict[str, Any] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class CompletionChoice:
    """CompletionChoice represents one of potentially multiple completions (OpenAI n > 1)."""
    index: int
    message: Message
    stop_reason: StopReason
    native_stop_reason: str


@dataclass(kw_only=True)
class SafetyRating:
    """SafetyRating is a Gemini per-category safety assessment."""
    category: str
    probability: str
    blocked: bool | None = None


@dataclass(kw_only=True)
class SafetySetting:
    """SafetySetting configures Gemini safety thresholds."""
    category: str
    threshold: str


@dataclass(kw_only=True)
class LogProbs:
    """LogProbs contains OpenAI token log probability data."""
    content: list[TokenLogProb] | None = None


@dataclass(kw_only=True)
class TokenLogProb:
    """TokenLogProb is the log probability for a single token."""
    token: str
    logprob: float
    bytes: list[int] | None = None
    top_logprobs: list[TopLogProb] | None = None


@dataclass(kw_only=True)
class TopLogProb:
    """TopLogProb is one of the top-k alternative tokens."""
    token: str
    logprob: float
    bytes: list[int] | None = None


# ────────────────────────────────────────
# source: runner.go

# RunnerMessageType discriminates the polymorphic RunnerMessage envelope.
RunnerMessageType = str

RunnerMsgHello: RunnerMessageType = "hello"
RunnerMsgWelcome: RunnerMessageType = "welcome"
RunnerMsgError: RunnerMessageType = "error"
RunnerMsgPing: RunnerMessageType = "ping"
RunnerMsgPong: RunnerMessageType = "pong"
RunnerMsgSpawn: RunnerMessageType = "spawn"
RunnerMsgStdin: RunnerMessageType = "stdin"
RunnerMsgSignal: RunnerMessageType = "signal"
RunnerMsgStdout: RunnerMessageType = "stdout"
RunnerMsgStderr: RunnerMessageType = "stderr"
RunnerMsgExit: RunnerMessageType = "exit"
RunnerMsgSeedDelta: RunnerMessageType = "seed_delta"
RunnerMsgSeedSnapshot: RunnerMessageType = "seed_snapshot"


@dataclass(kw_only=True)
class RunnerMessage:
    """RunnerMessage is the envelope for every frame exchanged on the runner WS. Exactly one payload field is populated, matching Type."""
    type: RunnerMessageType
    session_id: str | None = None
    hello: RunnerHello | None = None
    welcome: RunnerWelcome | None = None
    error: RunnerError | None = None
    spawn: RunnerSpawn | None = None
    stdin: RunnerStdin | None = None
    stdout: RunnerStdout | None = None
    stderr: RunnerStderr | None = None
    signal: RunnerSignal | None = None
    exit: RunnerExit | None = None
    seed_delta: RunnerSeedDelta | None = None
    seed_snapshot: RunnerSeedSnapshot | None = None


@dataclass(kw_only=True)
class RunnerHello:
    """RunnerHello is sent by the runner immediately after the WS upgrade. Authentication is the Authorization: Bearer header on the upgrade request — the server resolves the token to a Machine row by hash. The Hello payload is environmental detail the server records for display + binary-serving (hostname, OS, etc.); it carries no identity claims of its own. The machine label is server-side state, returned to the runner via Welcome.MachineName."""
    hostname: str  # os.Hostname()
    os: str  # GOOS
    arch: str  # GOARCH
    user: str  # os/user.Current().Username
    working_dir: str  # default cwd for spawned subprocesses
    available_harnesses: list[HarnessAvailable]  # detected harness binaries on this machine
    runner_version: str  # build-stamped version


@dataclass(kw_only=True)
class HarnessAvailable:
    """HarnessAvailable reports a harness binary present on the runner machine."""
    harness: Harness
    binary: str  # absolute path
    version: str | None = None


@dataclass(kw_only=True)
class RunnerWelcome:
    """RunnerWelcome is the server's ack of a successful Hello.  MachineName is the canonical name on the server side. Runners with a stale local label (e.g. machine renamed in the UI after enrollment) should overwrite their saved config from this value so subsequent connects don't keep reporting the old name."""
    machine_id: str  # server-assigned, stable across reconnects
    machine_name: str  # authoritative current name
    server_version: str
    ping_interval_secs: int  # app-level ping cadence the runner should follow
    accepted_at: str


@dataclass(kw_only=True)
class RunnerError:
    """RunnerError reports a fatal error before the connection is closed. Code is a stable machine-readable token; Message is human prose."""
    code: str  # "auth_failed", "duplicate_machine", "internal", …
    message: str


@dataclass(kw_only=True)
class RunnerSpawn:
    """RunnerSpawn asks the runner to fork a harness subprocess for a session. StartParams is the same payload the local subprocess transport sends to the harness as the "start" JSON-RPC method — the runner writes it verbatim to the subprocess's stdin as the first line.  Provision lists long-lived backend services the wrapper expects to be running on the same host (e.g. inber-server for the inber wrapper). The runner ensures each is installed and running before the fork — idempotently, so subsequent spawns don't restart a healthy backend. This is how "create an instance on a remote machine" actually deploys the harness's full stack to that machine."""
    harness: Harness
    binary_path: str | None = None  # optional override; runner falls back to PATH lookup
    working_dir: str | None = None  # overrides Hello.WorkingDir for this session
    start_params: dict[str, Any]  # verbatim JSON-RPC params for "start"
    env: list[str] | None = None  # extra env vars for the wrapper, "KEY=VALUE" form
    provision: list[HarnessService] | None = None  # backend services the runner should ensure are running


@dataclass(kw_only=True)
class HarnessService:
    """HarnessService describes one long-lived backend daemon a harness needs running on the runner host. The bridge populates this from its own per-harness deployment manifest, with credential values already resolved into Env so the runner doesn't need bridge-side state."""
    name: str  # unique key, e.g. "inber-server"; runners dedupe by this across spawns
    binary_url: str  # canonical /api/runner/binary?name=…&os=…&arch=… URL
    binary_path: str | None = None  # absolute path on the runner; defaults to ~/.local/bin/<name>
    args: list[str] | None = None  # command-line args passed to the binary
    env: list[str] | None = None  # env vars (KEY=VALUE), including resolved credential values
    health_url: str  # GET probe to wait for after start (e.g. http://localhost:8200/health)
    stdout: str | None = None  # optional log file path; defaults to ~/.cache/llm-bridge-runner/<name>.log


@dataclass(kw_only=True)
class RunnerStdin:
    """RunnerStdin carries one line (no trailing newline) of NDJSON to be written to the subprocess stdin, with a newline appended by the runner."""
    data: str


@dataclass(kw_only=True)
class RunnerStdout:
    """RunnerStdout carries one line (no trailing newline) read from the subprocess stdout. The server's existing pipeline parses it as msg.Event."""
    data: str


@dataclass(kw_only=True)
class RunnerStderr:
    """RunnerStderr carries one line of subprocess stderr, forwarded for server-side logging. Not parsed."""
    data: str

# RunnerSignalType is the kind of signal to deliver to a subprocess.
RunnerSignalType = str

RunnerSignalInterrupt: RunnerSignalType = "interrupt"
RunnerSignalKill: RunnerSignalType = "kill"


@dataclass(kw_only=True)
class RunnerSignal:
    """RunnerSignal asks the runner to deliver a signal to a session's subprocess."""
    signal: RunnerSignalType


@dataclass(kw_only=True)
class RunnerExit:
    """RunnerExit reports that a session's subprocess has exited."""
    exit_code: int
    error: str | None = None  # non-empty if the process couldn't be reaped cleanly

# SeedSource discriminates which store provided a seeded file. Lets the runner reconcile each provider against its own endpoint set without the bridge needing per-source message types.
SeedSource = str

SeedSourceAgentStore: SeedSource = "agent-store"
SeedSourceSkillStore: SeedSource = "skill-store"

# SeedOp is the kind of change the runner should apply to a seeded path.
SeedOp = str

SeedOpUpsert: SeedOp = "upsert"
SeedOpDelete: SeedOp = "delete"


@dataclass(kw_only=True)
class RunnerSeedDelta:
    """RunnerSeedDelta is a single-file change pushed to a runner immediately after the bridge records a new authoritative version. The runner must:   1. Compute the sha256 of the local file at InstallPath, if any.  2. If the local sha differs from ExpectedPriorSHA (drift), POST the local     bytes to the source's /seed/drift endpoint *first*. Only if that call     succeeds may it proceed to step 3.  3. GET the new content from the source's version endpoint and write it     atomically (tmp + rename).  ExpectedPriorSHA empty = the runner has never seen this file (first push). In that case any pre-existing content at InstallPath is treated as drift."""
    source: SeedSource
    op: SeedOp
    tracked_id: int  # ID in the source store
    version_id: int | None = None  # version to fetch on upsert
    install_path: str  # $HOME-relative
    new_sha: str | None = None  # sha of the new content (upsert only)
    expected_prior_sha: str | None = None  # last-pushed sha bridge thinks runner has


@dataclass(kw_only=True)
class RunnerSeedSnapshot:
    """RunnerSeedSnapshot tells the runner to do a full manifest reconcile against the named source. Sent on connect and after a bridge-side scan completes. The actual manifest is fetched via HTTP — this message is just the trigger + opportunity to bundle metadata (e.g. ticket count) for telemetry."""
    source: SeedSource
    entry_count: int | None = None  # bridge's count, for sanity logging
    reason: str | None = None  # "connect", "scan", "manual", …


# ────────────────────────────────────────
# source: server.go

# SessionMode selects the I/O contract for a session at spawn time.  SessionModeEvents (default) runs the harness in its current structured- events posture: stdin/stdout NDJSON between server and harness, normalized msg.Event stream over GET /sessions/{id}/events.  SessionModePTY runs the harness's upstream CLI inside a pseudoterminal the caller attaches to over a WebSocket at GET /sessions/{id}/attach. Bytes pass through verbatim — no msg.Event derivation. Per-harness opt-in via bridge.PTYCapableHarness.
SessionMode = str

SessionModeEvents: SessionMode = "events"
SessionModePTY: SessionMode = "pty"

# SessionType categorizes a session by how it is being used. Bridge-side behavior that depends on category (e.g. completion notifications, SSE keepalive policy) reads SessionType. Behavior that depends on which specific service originated the session reads Source.  Will be required on Create — the field is currently optional in the wire format for backward compatibility while callers are updated. Enforcement flips on once all callers populate it. See MIGRATION-session-identity.md.
SessionType = str

SessionTypeInteractive: SessionType = "interactive"
SessionTypeAutonomous: SessionType = "autonomous"
SessionTypeSystem: SessionType = "system"


@dataclass(kw_only=True)
class ManagedSession:
    """ManagedSession is a session as tracked by llm-bridge-server. This is the server's lightweight session management entity, distinct from [Session] which models rich agent-level state (usage, tasks, context).  Identifier fields:   - SessionID: canonical session id. Caller-minted on Create or     server-minted (br_<nanos>) when omitted. Stable from creation.   - HarnessSessionID: the canonical harness session ID (e.g. CC UUID).     Rotates on resume/fork. Empty until the harness reports it on first     event. Will move to adapter-private storage in Phase II.C."""
    session_id: str
    harness_session_id: str | None = None
    display_name: str
    harness: Harness
    instance_id: str | None = None
    state: str
    pid: int | None = None
    agent_id: str | None = None
    spawner_id: str | None = None
    parent_id: str | None = None
    harness_config: dict[str, Any] | None = None  # opaque harness-specific config
    info: SessionInfo | None = None  # latest session info reported by the harness
    folder_name: str | None = None  # user-assigned sidebar folder; empty = unfiled
    source: str | None = None  # origin tag carried from the creator (e.g. "scheduler", "autoworker"); empty = interactive
    session_type: SessionType | None = None  # category of session; required on Create once enforcement flips on
    mode: SessionMode | None = None  # I/O mode picked at creation; empty = events (legacy default)
    created_at: str
    updated_at: str


@dataclass(kw_only=True)
class HarnessAgent:
    """HarnessAgent is one of the agents registered against a harness type. Surfaced by /harnesses/{name}/capabilities so frontends can offer a per-harness agent picker without re-querying agent-store."""
    name: str
    display_name: str | None = None
    description: str | None = None
    is_default: bool | None = None


@dataclass(kw_only=True)
class HarnessInfo:
    """HarnessInfo describes a registered harness type and its capabilities.  HookEvents lists the hook lifecycle events the bridge can register handlers against for this harness (e.g. Claude Code's "PreToolUse", "PostToolUse"…). Empty for harnesses with no registerable hook mechanism — harnesses that only emit observation-style lifecycle notifications or run agents remotely without local hook points."""
    name: str
    label: str
    emoji: str
    image: str | None = None
    tint: str | None = None
    available: bool
    binary: str | None = None
    capabilities: list[str]
    hook_events: list[str] | None = None
    supported_providers: list[str] | None = None
    pty: bool


@dataclass(kw_only=True)
class Credential:
    """Credential represents an API credential as exposed by the server. Sensitive fields are masked (api_key_masked, token_masked)."""
    id: str
    provider: str
    label: str
    auth_type: str
    api_key_masked: str | None = None
    token_masked: str | None = None
    priority: int
    enabled: bool
    expires_at: int
    error_count: int | None = None
    last_error: str | None = None


@dataclass(kw_only=True)
class HarnessDefaults:
    """HarnessDefaults stores per-harness configuration defaults."""
    model: str | None = None
    effort: str | None = None
    max_budget: float | None = None
    disabled_tools: list[str] | None = None
    permission_mode: str | None = None


@dataclass(kw_only=True)
class BridgePrefs:
    """BridgePrefs stores user preferences for the bridge dashboard."""
    last_harness: str | None = None
    last_instance_id: str | None = None
    last_session: dict[str, str] | None = None
    last_instance: dict[str, str] | None = None
    defaults: dict[str, HarnessDefaults] | None = None
    bypass_permissions: bool | None = None


@dataclass(kw_only=True)
class MaterializedMessage:
    """MaterializedMessage is a flattened message returned by the messages API. Assembled from raw events by log-store: stream deltas are concatenated, tool calls are collected, and the final ResultEvent becomes Meta."""
    id: str | None = None  # canonical bridge MessageID
    harness_message_id: str | None = None  # harness-native id, if known
    role: str
    content: str
    thinking: str | None = None
    tools: list[MaterializedTool] | None = None
    meta: ResultEvent | None = None
    events: list[dict[str, Any]] | None = None
    timestamp: str
    done: bool


@dataclass(kw_only=True)
class MaterializedTool:
    """MaterializedTool records a tool invocation within a materialized message."""
    tool_id: str
    tool: str
    input: dict[str, Any] | None = None
    output: str | None = None
    error: bool | None = None


@dataclass(kw_only=True)
class SessionAggregate:
    """SessionAggregate is the per-session token/cost summary returned by GET /api/v1/sessions/aggregates. Computed by SUMming the result events stored for each session — no separate aggregate table. Model is the most recent value reported across the session's result events."""
    session_id: str
    turns: int
    input_tokens: int
    output_tokens: int
    cost_usd: float
    duration_ms: int
    model: str | None = None


@dataclass(kw_only=True)
class HealthResponse:
    """HealthResponse is the server's health check response."""
    status: str
    harnesses: list[HarnessInfo]
    sessions: SessionCounts


@dataclass(kw_only=True)
class SessionCounts:
    """SessionCounts is a breakdown of active sessions by state."""
    running: int
    idle: int
    completed: int

# ConformanceFeature is a capability that a harness may or may not support.
ConformanceFeature = str


@dataclass(kw_only=True)
class ConformanceTestResult:
    """ConformanceTestResult records the outcome of a single feature test."""
    feature: ConformanceFeature
    passed: bool
    skipped: bool | None = None
    error: str | None = None
    duration: str | None = None


@dataclass(kw_only=True)
class ConformanceHarnessResult:
    """ConformanceHarnessResult records all test results for a single harness."""
    harness: str
    binary: str
    tested_at: str
    results: list[ConformanceTestResult]
    summary: ConformanceSummary


@dataclass(kw_only=True)
class ConformanceSummary:
    """ConformanceSummary counts test outcomes."""
    total: int
    passed: int
    failed: int
    skipped: int


@dataclass(kw_only=True)
class ConformanceMatrix:
    """ConformanceMatrix holds conformance results for all tested harnesses."""
    generated_at: str
    harnesses: list[ConformanceHarnessResult]


@dataclass(kw_only=True)
class CreateSessionRequest:
    """CreateSessionRequest is the request body for POST /sessions.  SessionID is the caller-minted session identifier. When set, the bridge uses it as the session's primary key and rejects collisions with 409. When empty, the bridge mints one (br_<nanos>). Caller-mints lets workers (autoworker, scheduler, etc.) hold a synchronous handle for kanban links before the create round-trip returns; interactive callers may leave it empty and consume the server-minted value. Recommended caller format: ULID. See MIGRATION-session-identity.md.  Source is an origin tag set by the caller identifying what created this session (e.g. "scheduler", "autoworker"). Interactive UI callers leave it empty. The server persists it on the session and may auto-assign a folder based on the value (see LLMBRIDGE_SOURCE_FOLDERS).  SessionType categorizes the session (interactive / autonomous / system). Currently optional for backward compatibility; will be required once all callers are updated. See MIGRATION-session-identity.md."""
    harness: Harness
    session_id: str | None = None
    instance_id: str | None = None
    display_name: str | None = None
    agent_id: str | None = None
    spawner_id: str | None = None
    auto_start: bool | None = None
    source: str | None = None
    session_type: SessionType | None = None
    harness_config: dict[str, Any] | None = None  # opaque harness-specific config, merged into start params
    mode: SessionMode | None = None


@dataclass(kw_only=True)
class SendMessageRequest:
    """SendMessageRequest is the request body for POST /sessions/{id}/send.  Either Message (plain text) or Blocks (canonical content-block array for multimodal input — text, images, documents) carries the user's turn. The two are mutually exclusive: setting both is rejected at the server boundary so harnesses never have to disambiguate downstream.  ClientRequestID is a caller-minted identifier for this turn. The bridge stamps it on every event it emits for the turn so producers can correlate server-side state with their own outbound request. Optional — callers that don't need correlation can leave it empty."""
    message: str
    blocks: list[ContentBlock] | None = None
    client_request_id: str | None = None


@dataclass(kw_only=True)
class ForkSessionRequest:
    """ForkSessionRequest is the request body for POST /sessions/{id}/fork."""
    display_name: str | None = None
    session_type: SessionType | None = None


@dataclass(kw_only=True)
class CompactSessionRequest:
    """CompactSessionRequest is the request body for POST /sessions/{id}/compact."""
    summary: str | None = None


@dataclass(kw_only=True)
class ConfigSessionRequest:
    """ConfigSessionRequest is the request body for POST /sessions/{id}/config."""
    model: str | None = None
    effort: str | None = None
    disabled_tools: list[str] | None = None
    max_budget: float | None = None


@dataclass(kw_only=True)
class CreateInstanceRequest:
    """CreateInstanceRequest is the request body for POST /instances. MachineID is required — instances always belong to a machine. Use CreateMachineRequest first (or have a runner enroll) to obtain one."""
    harness_type: str
    name: str
    machine_id: str
    working_dir: str | None = None
    max_concurrent_sessions: int | None = None


@dataclass(kw_only=True)
class CreateMachineRequest:
    """CreateMachineRequest is the request body for POST /machines."""
    name: str
    emoji: str | None = None
    hostname: str | None = None
    os: str | None = None
    arch: str | None = None
    transport: Transport
    ssh_user: str | None = None
    ssh_key_path: str | None = None
    ssh_port: int | None = None
    default_working_dir: str | None = None
    notes: str | None = None


@dataclass(kw_only=True)
class UpdateMachineRequest:
    """UpdateMachineRequest patches a machine. Empty fields are left unchanged."""
    name: str | None = None
    emoji: str | None = None
    hostname: str | None = None
    os: str | None = None
    arch: str | None = None
    transport: Transport | None = None
    ssh_user: str | None = None
    ssh_key_path: str | None = None
    ssh_port: int | None = None
    default_working_dir: str | None = None
    notes: str | None = None


@dataclass(kw_only=True)
class MintEnrollmentRequest:
    """MintEnrollmentRequest creates a one-time enrollment passphrase for a runner. TTLSeconds defaults to 900 (15 min) on the server when zero."""
    ttl_seconds: int | None = None


@dataclass(kw_only=True)
class MintEnrollmentResponse:
    """MintEnrollmentResponse carries the freshly-minted passphrase. The server stores only its hash; this is the only chance to capture the plaintext."""
    passphrase: str
    expires_at: str


@dataclass(kw_only=True)
class EnrollRunnerRequest:
    """EnrollRunnerRequest is the request body for POST /api/runner/enroll. The passphrase is a single-use credential; the rest is the runner's self-report of its environment, used to populate the auto-created Machine row."""
    passphrase: str
    machine_name: str | None = None  # defaults to hostname
    hostname: str
    os: str
    arch: str
    user: str | None = None
    working_dir: str | None = None
    available_harnesses: list[HarnessAvailable] | None = None
    runner_version: str | None = None


@dataclass(kw_only=True)
class EnrollRunnerResponse:
    """EnrollRunnerResponse returns the durable per-machine token the runner will present on subsequent WS connections. Save it locally; the server stores only its hash."""
    machine_id: str
    machine_name: str
    runner_token: str
    instance_ids: list[str]  # default instances auto-created for this machine


@dataclass(kw_only=True)
class BindCredentialRequest:
    """BindCredentialRequest is the request body for POST /instances/{id}/credentials."""
    credential_id: str
    priority: int


@dataclass(kw_only=True)
class RenameSessionRequest:
    """RenameSessionRequest is the request body for POST /sessions/{id}/rename."""
    display_name: str


@dataclass(kw_only=True)
class SourceFolderMapping:
    """SourceFolderMapping is one row of the runtime source→folder map. Default=true means the value comes from the env-var defaults (LLMBRIDGE_SOURCE_FOLDERS) with no runtime override; Default=false means the row originates from the source_folders table. UpdatedAt is zero for env defaults."""
    source: str
    folder_name: str
    default: bool
    updated_at: str | None = None


@dataclass(kw_only=True)
class PutSourceFolderRequest:
    """PutSourceFolderRequest is the request body for PUT /source-folders/{source}. FolderName must reference an existing folder (validated server-side). ApplyToExisting=true rebuckets prior sessions whose folder is empty or matches the previous effective folder for this source; manual moves are preserved."""
    folder_name: str
    apply_to_existing: bool | None = None


@dataclass(kw_only=True)
class SourceFolderApplyResult:
    """SourceFolderApplyResult is the response payload for PUT/DELETE when ApplyToExisting was requested. Updated is the row count from the rebucket UPDATE."""
    mapping: SourceFolderMapping
    updated: int


# ────────────────────────────────────────
# source: session.go


@dataclass(kw_only=True)
class Session:
    """Session represents an agent session across any harness."""
    id: str
    harness: Harness
    state: SessionState
    agent: str | None = None
    orchestrator: str | None = None
    model: str | None = None
    created_at: str
    last_active: str
    ended_at: str | None = None
    context_tokens: int | None = None
    context_limit: int | None = None
    total_usage: TokenUsage
    total_cost: Cost | None = None
    turn_count: int
    config: dict[str, Any] | None = None
    tasks: list[SessionTask] | None = None
    active_request: str | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class SessionTask:
    """SessionTask tracks a task within a session."""
    content: str
    status: str
    active_form: str | None = None


@dataclass(kw_only=True)
class StoredSession:
    """StoredSession represents a session discovered on disk from a harness's native storage (e.g. ~/.claude/projects/ or ~/.codex/sessions/). These are sessions that exist outside the llm-bridge-server's own store."""
    harness_session_id: str
    bridge_session_id: str | None = None
    harness: Harness
    project: str | None = None  # project directory or context
    prompt: str | None = None  # initial prompt snippet
    created_at: str
    updated_at: str  # file modification time
    path: str  # on-disk path to session file
    turn_count: int | None = None  # approximate number of turns
    source: str | None = None


# ────────────────────────────────────────
# source: session_meta.go


@dataclass(kw_only=True)
class FolderList:
    """FolderList is the ordered list of user-defined folder names for organizing sessions in the sidebar. Folder assignment per session lives on [ManagedSession.FolderName] so it travels with the session row."""
    folder_order: list[str]


@dataclass(kw_only=True)
class CreateFolderRequest:
    """CreateFolderRequest is the body for POST /folders."""
    name: str


@dataclass(kw_only=True)
class RenameFolderRequest:
    """RenameFolderRequest is the body for PUT /folders/{name}."""
    new_name: str


@dataclass(kw_only=True)
class SetSessionFolderRequest:
    """SetSessionFolderRequest is the body for PUT /sessions/{id}/folder. An empty Folder string clears the assignment (un-files the session)."""
    folder: str


@dataclass(kw_only=True)
class FileInactiveRequest:
    """FileInactiveRequest is the body for POST /admin/file-inactive.  Sessions whose updated_at is older than InactiveDays and which are not already filed move into Folder. Folder is auto-created if it doesn't exist in the registry."""
    inactive_days: int
    folder: str


@dataclass(kw_only=True)
class FileInactiveResponse:
    """FileInactiveResponse reports the outcome of a file-inactive sweep."""
    moved: int
    folder: str
    ids: list[str] | None = None


@dataclass(kw_only=True)
class ArchiveOldRequest:
    """ArchiveOldRequest is the body for POST /admin/archive-old.  Every session (in any folder other than the Archive folder) whose updated_at is older than InactiveDays and which is not currently running moves into the Archive folder. The Archive folder is auto-created if it doesn't exist in the registry."""
    inactive_days: int


@dataclass(kw_only=True)
class ArchiveOldResponse:
    """ArchiveOldResponse reports the outcome of an archive-old sweep."""
    moved: int
    ids: list[str] | None = None


@dataclass(kw_only=True)
class MarkSessionDoneRequest:
    """MarkSessionDoneRequest is the body for POST /sessions/{id}/mark-done.  Done=true atomically (a) emits an EventSessionState{State: completed} through the central derivation pipeline so the row state and SSE feed agree, and (b) moves the session into the canonical Archive folder. Done=false reverses both: state goes to idle, folder is cleared.  If new events flow in after the manual mark, derivation overwrites the state (e.g. a new tool_call flips back to tool_running). That's intentional — the session re-engaging visibly says "no longer done"."""
    done: bool


# ────────────────────────────────────────
# source: stream.go

# StreamEventType identifies the kind of streaming event.
StreamEventType = str

StreamEventStart: StreamEventType = "stream_start"
StreamEventContentBlockStart: StreamEventType = "content_block_start"
StreamEventContentBlockDelta: StreamEventType = "content_block_delta"
StreamEventContentBlockStop: StreamEventType = "content_block_stop"
StreamEventMessageDelta: StreamEventType = "message_delta"
StreamEventMessageStop: StreamEventType = "message_stop"
StreamEventPing: StreamEventType = "ping"
StreamEventError: StreamEventType = "error"


@dataclass(kw_only=True)
class StreamEvent:
    """StreamEvent is the unified streaming event type. Follows Anthropic's granular model (most expressive) and synthesizes block-level events for providers that don't have them (OpenAI, Gemini)."""
    type: StreamEventType
    start: StreamStart | None = None
    block_start: BlockStart | None = None
    block_delta: BlockDelta | None = None
    block_stop: BlockStop | None = None
    msg_delta: MessageDelta | None = None
    error: StreamError | None = None
    raw: dict[str, Any] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class StreamStart:
    """StreamStart carries initial message metadata."""
    id: str
    model: str
    provider: Provider
    usage: TokenUsage


@dataclass(kw_only=True)
class BlockStart:
    """BlockStart signals a new content block beginning."""
    index: int
    block: ContentBlock

# DeltaType identifies the kind of streaming delta.
DeltaType = str

DeltaText: DeltaType = "text_delta"
DeltaInputJSON: DeltaType = "input_json_delta"
DeltaThinking: DeltaType = "thinking_delta"
DeltaSignature: DeltaType = "signature_delta"
DeltaAudio: DeltaType = "audio_delta"


@dataclass(kw_only=True)
class BlockDelta:
    """BlockDelta carries incremental content for a block."""
    index: int
    type: DeltaType
    text: str | None = None
    partial_json: str | None = None
    thinking: str | None = None
    signature: str | None = None
    audio_data: str | None = None


@dataclass(kw_only=True)
class BlockStop:
    """BlockStop signals a content block has finished."""
    index: int


@dataclass(kw_only=True)
class MessageDelta:
    """MessageDelta carries end-of-message metadata."""
    stop_reason: StopReason
    native_stop_reason: str | None = None
    stop_sequence: str | None = None
    usage: TokenUsage


@dataclass(kw_only=True)
class StreamError:
    """StreamError represents an error during streaming."""
    type: str
    message: str
    code: str | None = None
    retryable: bool | None = None
    retry_after_ms: int | None = None
    status_code: int | None = None


# ────────────────────────────────────────
# source: tool.go


@dataclass(kw_only=True)
class ToolDef:
    """ToolDef defines a tool the model can call."""
    name: str
    description: str
    input_schema: dict[str, Any]
    strict: bool | None = None
    cache_control: CacheControl | None = None
    _overflow: dict[str, dict[str, Any]] | None = None

# ToolChoiceMode determines how the model selects tools.
ToolChoiceMode = str

ToolChoiceAuto: ToolChoiceMode = "auto"
ToolChoiceAny: ToolChoiceMode = "any"
ToolChoiceNone: ToolChoiceMode = "none"
ToolChoiceRequired: ToolChoiceMode = "required"
ToolChoiceSpecific: ToolChoiceMode = "specific"


@dataclass(kw_only=True)
class ToolChoice:
    """ToolChoice controls model tool selection behavior."""
    mode: ToolChoiceMode
    name: str | None = None
    disable_parallel: bool | None = None


# ────────────────────────────────────────
# source: usage.go


@dataclass(kw_only=True)
class TokenUsage:
    """TokenUsage tracks token consumption across all providers."""
    input_tokens: int
    output_tokens: int
    total_tokens: int
    cache_read_tokens: int | None = None
    cache_write_tokens: int | None = None
    reasoning_tokens: int | None = None
    context_tokens: int | None = None
    context_limit: int | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class Cost:
    """Cost tracks monetary cost of a request."""
    total_usd: float
    input_usd: float | None = None
    output_usd: float | None = None
    is_byok: bool | None = None
    upstream_cost: float | None = None


# ────────────────────────────────────────
# source: validate.go


@dataclass(kw_only=True)
class ValidationError:
    """ValidationError contains one or more validation failures."""
    failures: list[ValidationFailure]


@dataclass(kw_only=True)
class ValidationFailure:
    """ValidationFailure describes a single validation issue."""
    path: str
    code: str
    message: str

# Validation error codes — conversation/response.
ErrEmptyField = "empty_field"
ErrInvalidRole = "invalid_role"
ErrInvalidBlockType = "invalid_block_type"
ErrMultipleBlocksSet = "multiple_blocks_set"
ErrNoBlockSet = "no_block_set"
ErrMissingToolID = "missing_tool_id"
ErrMissingToolName = "missing_tool_name"
ErrOrphanedToolResult = "orphaned_tool_result"
ErrAlternationViolation = "alternation_violation"
ErrMissingModel = "missing_model"
ErrMissingProvider = "missing_provider"
ErrInvalidStopReason = "invalid_stop_reason"
ErrThinkingNoSignature = "thinking_no_signature"
ErrOpaqueDataModified = "opaque_data_modified"

# Validation error codes — event/session.
ErrMissingSessionID = "missing_session_id"
ErrMissingBridgeSessionID = "missing_bridge_session_id"
ErrMissingHarness = "missing_harness"
ErrInvalidEventType = "invalid_event_type"
ErrNoEventPayload = "no_event_payload"
ErrMultiplePayloads = "multiple_payloads"
ErrInvalidSessionState = "invalid_session_state"
ErrMissingTimestamp = "missing_timestamp"
