# AUTO-GENERATED — DO NOT EDIT THIS FILE.
#
# Generated from github.com/kayushkin/llm-bridge/msg @ f7b290ea0ca610b4e5c56b67693d278db3722efe
# Source of truth: Go types in msg/*.go
# To regenerate: ./generate-py.sh
#
# Any manual changes will be overwritten on the next generation run.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


# ────────────────────────────────────────
# source: config.go


@dataclass(kw_only=True)
class GenerationConfig:
    """GenerationConfig holds provider-agnostic generation parameters."""
    max_tokens: int | None = None
    temperature: float | None = None
    top_p: float | None = None
    top_k: int | None = None
    stop_sequences: list[str] | None = None
    stream: bool | None = None
    response_format: ResponseFormat | None = None


@dataclass(kw_only=True)
class ResponseFormat:
    """ResponseFormat specifies structured output requirements."""
    type: str
    json_schema: dict[str, Any] | None = None
    strict: bool | None = None


@dataclass(kw_only=True)
class AnthropicConfig:
    """AnthropicConfig holds Anthropic-specific request parameters."""
    thinking_budget: int | None = None
    thinking_display: str | None = None
    effort: str | None = None
    container_id: str | None = None
    service_tier: str | None = None
    inference_geo: str | None = None
    assistant_prefill: list[ContentBlock] | None = None
    metadata: dict[str, str] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class OpenAIConfig:
    """OpenAIConfig holds OpenAI-specific request parameters."""
    prediction: str | None = None
    logprobs: bool | None = None
    top_logprobs: int | None = None
    n: int | None = None
    frequency_penalty: float | None = None
    presence_penalty: float | None = None
    seed: int | None = None
    stream_include_usage: bool | None = None
    store: bool | None = None
    previous_response_id: str | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class GeminiConfig:
    """GeminiConfig holds Gemini-specific request parameters."""
    safety_settings: list[SafetySetting] | None = None
    cached_content: str | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class OpenRouterConfig:
    """OpenRouterConfig holds OpenRouter-specific request parameters."""
    models: list[str] | None = None
    route: str | None = None
    provider_prefs: OpenRouterProviderPrefs | None = None
    plugins: list[OpenRouterPlugin] | None = None
    debug: bool | None = None
    top_a: float | None = None
    min_p: float | None = None
    repetition_penalty: float | None = None
    prediction: str | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class OpenRouterProviderPrefs:
    """OpenRouterProviderPrefs controls model routing preferences."""
    order: list[str] | None = None
    allow_fallbacks: bool | None = None
    require_parameters: bool | None = None


@dataclass(kw_only=True)
class OpenRouterPlugin:
    """OpenRouterPlugin is an OpenRouter plugin configuration."""
    id: str
    enabled: bool


# ────────────────────────────────────────
# source: content.go

# BlockType identifies the kind of content block.
BlockType = str

BlockText: BlockType = "text"
BlockImage: BlockType = "image"
BlockAudio: BlockType = "audio"
BlockVideo: BlockType = "video"
BlockDocument: BlockType = "document"
BlockToolUse: BlockType = "tool_use"
BlockToolResult: BlockType = "tool_result"
BlockThinking: BlockType = "thinking"
BlockRedactedThinking: BlockType = "redacted_thinking"
BlockCodeExec: BlockType = "code_exec"
BlockCodeExecResult: BlockType = "code_exec_result"
BlockServerToolResult: BlockType = "server_tool_result"
BlockRefusal: BlockType = "refusal"


@dataclass(kw_only=True)
class ContentBlock:
    """ContentBlock is a discriminated union of all possible content block types. Exactly one of the typed fields will be non-nil, matching Type."""
    type: BlockType
    text_block: TextBlock | None = None
    image_block: ImageBlock | None = None
    audio_block: AudioBlock | None = None
    video_block: VideoBlock | None = None
    document_block: DocumentBlock | None = None
    tool_use_block: ToolUseBlock | None = None
    tool_result_block: ToolResultBlock | None = None
    thinking_block: ThinkingBlock | None = None
    redacted_thinking_block: RedactedThinkingBlock | None = None
    code_exec_block: CodeExecBlock | None = None
    code_exec_result_block: CodeExecResultBlock | None = None
    server_tool_result_block: ServerToolResultBlock | None = None
    refusal_block: RefusalBlock | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class TextBlock:
    """TextBlock represents plain text content."""
    text: str
    citations: list[Citation] | None = None
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class Citation:
    """Citation references a source document by character position."""
    type: str
    cited_text: str
    document_index: int
    start_char_index: int | None = None
    end_char_index: int | None = None
    start_page: int | None = None
    end_page: int | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class CacheControl:
    """CacheControl is Anthropic's per-block cache hint."""
    type: str  # "ephemeral"
    ttl: str | None = None

# MediaSourceKind identifies how media data is provided.
MediaSourceKind = str

MediaBase64: MediaSourceKind = "base64"
MediaURL: MediaSourceKind = "url"
MediaFileID: MediaSourceKind = "file_id"


@dataclass(kw_only=True)
class MediaSource:
    """MediaSource unifies how media (images, audio, video, docs) are referenced."""
    kind: MediaSourceKind
    media_type: str
    data: str
    detail: str | None = None
    format: str | None = None
    filename: str | None = None


@dataclass(kw_only=True)
class ImageBlock:
    """ImageBlock represents an image in any encoding."""
    source: MediaSource
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class AudioBlock:
    """AudioBlock represents audio content."""
    source: MediaSource
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class VideoBlock:
    """VideoBlock represents video content."""
    source: MediaSource
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class DocumentBlock:
    """DocumentBlock represents a document (PDF, plain text, etc.)."""
    source: MediaSource
    title: str | None = None
    citations_enabled: bool | None = None
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class ToolUseBlock:
    """ToolUseBlock represents the model requesting a tool call."""
    id: str
    original_id: str
    name: str
    input: dict[str, Any]
    cache_control: CacheControl | None = None


@dataclass(kw_only=True)
class ToolResultBlock:
    """ToolResultBlock represents the result of a tool call."""
    tool_use_id: str
    original_tool_use_id: str
    content: list[ContentBlock] | None = None
    is_error: bool | None = None
    source_role: str | None = None
    tool_name: str | None = None


@dataclass(kw_only=True)
class ThinkingBlock:
    """ThinkingBlock represents model reasoning/thinking traces."""
    text: str
    signature: str | None = None
    budget_tokens: int | None = None


@dataclass(kw_only=True)
class RedactedThinkingBlock:
    """RedactedThinkingBlock represents thinking content redacted by the provider."""
    data: str


@dataclass(kw_only=True)
class CodeExecBlock:
    """CodeExecBlock represents a code execution request."""
    language: str
    code: str


@dataclass(kw_only=True)
class CodeExecResultBlock:
    """CodeExecResultBlock represents the output of code execution."""
    outcome: str
    output: str


@dataclass(kw_only=True)
class ServerToolResultBlock:
    """ServerToolResultBlock represents results from provider-hosted tools."""
    tool_type: str
    content: dict[str, Any]
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class RefusalBlock:
    """RefusalBlock represents the model explicitly refusing a request."""
    text: str


# ────────────────────────────────────────
# source: event.go


@dataclass(kw_only=True)
class Event:
    """Event is the unified harness event type. All harness-specific events are normalized into this structure."""
    type: EventType
    harness: Harness
    session_id: str
    bridge_id: str | None = None
    client_id: str | None = None
    completion_id: str | None = None
    client_request_id: str | None = None
    message_id: str | None = None
    harness_message_id: str | None = None
    timestamp: str
    result: ResultEvent | None = None
    stream: HarnessStream | None = None
    tool_call: ToolCallEvent | None = None
    tool_result: ToolResultEvent | None = None
    thinking: ThinkingEvent | None = None
    plan: PlanEvent | None = None
    system: SystemEvent | None = None
    approval: ApprovalEvent | None = None
    error: ErrorEvent | None = None
    state: StateEvent | None = None
    info: SessionInfo | None = None
    raw: dict[str, Any] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class ResultEvent:
    """ResultEvent is a completed harness run."""
    text: str
    message: Message | None = None
    is_error: bool | None = None
    structured_output: dict[str, Any] | None = None
    usage: TokenUsage
    cost: Cost | None = None
    duration_ms: int | None = None
    duration_api_ms: int | None = None
    num_turns: int | None = None
    api_calls: int | None = None
    model: str | None = None
    api_call_usages: list[TokenUsage] | None = None
    tool_events: list[ToolSummary] | None = None


@dataclass(kw_only=True)
class ToolSummary:
    """ToolSummary records a tool invocation within a completed run."""
    tool: str
    input: str | None = None
    output: str | None = None
    error: str | None = None


@dataclass(kw_only=True)
class HarnessStream:
    """HarnessStream is a streaming text/content event from the harness. Named HarnessStream to avoid collision with StreamEvent (API-level streaming)."""
    delta: BlockDelta | None = None
    message_id: str | None = None
    hidden: bool | None = None


@dataclass(kw_only=True)
class ToolCallEvent:
    """ToolCallEvent is a tool being invoked."""
    tool_id: str
    name: str
    input: dict[str, Any]


@dataclass(kw_only=True)
class ToolResultEvent:
    """ToolResultEvent is the output of a tool invocation."""
    tool_id: str
    name: str
    output: str
    is_error: bool | None = None


@dataclass(kw_only=True)
class ThinkingEvent:
    """ThinkingEvent is a thinking/reasoning event."""
    text: str
    subtype: str | None = None  # "", "summary"


@dataclass(kw_only=True)
class PlanEvent:
    """PlanEvent is a structured task-planning event (distinct from thinking)."""
    text: str


@dataclass(kw_only=True)
class SystemEvent:
    """SystemEvent is a system-level notification."""
    subtype: str
    message: str | None = None
    attempt: int | None = None
    max_retries: int | None = None
    retry_delay_ms: int | None = None
    error_status: int | None = None
    error_type: str | None = None


@dataclass(kw_only=True)
class ApprovalEvent:
    """ApprovalEvent represents a permission request or response."""
    action: str
    status: str
    tool_name: str | None = None
    detail: str | None = None
    command: str | None = None
    path: str | None = None
    patch: str | None = None
    permissions: list[str] | None = None
    prompt: str | None = None


@dataclass(kw_only=True)
class ErrorEvent:
    """ErrorEvent represents a harness-level error."""
    code: str
    message: str
    retryable: bool | None = None
    status_code: int | None = None


@dataclass(kw_only=True)
class StateEvent:
    """StateEvent represents a session state change."""
    state: SessionState
    previous: SessionState | None = None
    reason: str | None = None


@dataclass(kw_only=True)
class SessionInfo:
    """SessionInfo describes what the harness knows about its session at start: the system prompt it was configured with, the working directory, and the tools / slash commands / sub-agents / MCP servers the underlying agent reports as available. Emitted by the harness as an EventSessionInfo after the agent's initial handshake, and persisted on ManagedSession so it can be retrieved via GET /sessions/{id} without replaying events."""
    system_prompt: str | None = None
    append_system_prompt: str | None = None
    working_dir: str | None = None
    model: str | None = None
    permission_mode: str | None = None
    tools: list[ToolInfo] | None = None
    slash_commands: list[str] | None = None
    agents: list[str] | None = None
    skills: list[str] | None = None
    mcp_servers: list[MCPServerInfo] | None = None


@dataclass(kw_only=True)
class ToolInfo:
    """ToolInfo names a tool the agent has available. Description is optional — the harness only reports what the underlying agent exposes; the UI may enrich with its own descriptions."""
    name: str
    description: str | None = None


@dataclass(kw_only=True)
class MCPServerInfo:
    """MCPServerInfo describes an MCP server connection reported by the agent."""
    name: str
    status: str | None = None


# ────────────────────────────────────────
# source: instance.go

# Transport specifies how to connect to a harness instance.
Transport = str

TransportLocal: Transport = "local"
TransportSSH: Transport = "ssh"


@dataclass(kw_only=True)
class Instance:
    """Instance represents a deployed harness on a specific machine. A harness type (claudecode, codex) is a template; an instance is a running deployment."""
    id: str
    harness_type: Harness
    name: str  # human label: "laptop-cc", "ci-runner-1"
    host: str  # "localhost", "dev.internal", "ci-01.example.com"
    transport: Transport
    ssh_user: str | None = None
    ssh_key_path: str | None = None
    ssh_port: int | None = None  # default 22
    working_dir: str | None = None
    max_concurrent_sessions: int
    enabled: bool
    created_at: str
    updated_at: str


@dataclass(kw_only=True)
class InstanceCredential:
    """InstanceCredential binds a credential to a harness instance with priority."""
    instance_id: str
    credential_id: str
    priority: int  # 0 = primary, 1+ = fallbacks
    enabled: bool


@dataclass(kw_only=True)
class InstanceStatus:
    """InstanceStatus aggregates runtime status for an instance."""
    instance: Instance
    active_sessions: int
    credentials: list[InstanceCredential]
    reachable: bool  # SSH connectivity check
    last_checked: str


# ────────────────────────────────────────
# source: message.go


@dataclass(kw_only=True)
class Conversation:
    """Conversation represents a complete request to an LLM API."""
    id: str | None = None
    model: str
    provider: Provider
    system: list[ContentBlock] | None = None
    messages: list[Message]
    tools: list[ToolDef] | None = None
    tool_choice: ToolChoice | None = None
    config: GenerationConfig
    provider_config: dict[str, Any] | None = None  # AnthropicConfig | OpenAIConfig | GeminiConfig | OpenRouterConfig
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class Message:
    """Message is a single turn in a conversation."""
    id: str | None = None
    role: Role
    content: list[ContentBlock]
    name: str | None = None
    native_role: NativeRole | None = None
    source_pattern: str | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


# ────────────────────────────────────────
# source: provider.go

# Provider identifies which LLM API produced or will consume a message.
Provider = str

ProviderAnthropic: Provider = "anthropic"
ProviderOpenAI: Provider = "openai"
ProviderGemini: Provider = "gemini"
ProviderOpenRouter: Provider = "openrouter"

# Role is the normalized message role across all providers.
Role = str

RoleSystem: Role = "system"
RoleUser: Role = "user"
RoleAssistant: Role = "assistant"
RoleTool: Role = "tool"


@dataclass(kw_only=True)
class NativeRole:
    """NativeRole maps to provider-specific role strings."""
    provider: Provider
    value: str  # e.g. "model" for Gemini, "developer" for OpenAI o-series

# StopReason is the normalized reason a completion ended.
StopReason = str

StopEnd: StopReason = "end"
StopMaxTokens: StopReason = "max_tokens"
StopToolUse: StopReason = "tool_use"
StopStopSequence: StopReason = "stop_sequence"
StopSafety: StopReason = "safety"
StopContentFilter: StopReason = "content_filter"
StopRecitation: StopReason = "recitation"
StopError: StopReason = "error"

# Harness identifies which agent harness produced an event.
Harness = str

HarnessClaudeCode: Harness = "claude_code"
HarnessCodex: Harness = "codex"
HarnessOpenClaw: Harness = "openclaw"
HarnessInber: Harness = "inber"
HarnessHermes: Harness = "hermes"
HarnessAider: Harness = "aider"
HarnessGoose: Harness = "goose"
HarnessAutohand: Harness = "autohand"
HarnessJig: Harness = "jig"
HarnessDexto: Harness = "dexto"
HarnessCommander: Harness = "commander"
HarnessNanoClaw: Harness = "nanoclaw"
HarnessCline: Harness = "cline"
HarnessRooCode: Harness = "roo_code"
HarnessKiloCode: Harness = "kilo_code"
HarnessOpenCode: Harness = "opencode"

# EventType classifies a harness event.
EventType = str

EventResult: EventType = "result"
EventStream: EventType = "stream"
EventToolCall: EventType = "tool_call"
EventToolResult: EventType = "tool_result"
EventThinking: EventType = "thinking"
EventSystem: EventType = "system"
EventApproval: EventType = "approval"
EventError: EventType = "error"
EventSessionState: EventType = "session_state"
EventPlan: EventType = "plan"
EventSessionInfo: EventType = "session_info"
EventUserMessage: EventType = "user_message"

# SessionState represents the current state of a harness session.
SessionState = str

SessionIdle: SessionState = "idle"
SessionRunning: SessionState = "running"
SessionCompleted: SessionState = "completed"
SessionError: SessionState = "error"
SessionAborted: SessionState = "aborted"
SessionWaitingApproval: SessionState = "waiting_on_approval"


# ────────────────────────────────────────
# source: response.go


@dataclass(kw_only=True)
class CompletionResponse:
    """CompletionResponse is the unified response from any LLM API."""
    id: str
    model: str
    provider: Provider
    message: Message
    stop_reason: StopReason
    native_stop_reason: str
    stop_sequence: str | None = None
    usage: TokenUsage
    cost: Cost | None = None
    safety_ratings: list[SafetyRating] | None = None
    system_fingerprint: str | None = None
    logprobs: LogProbs | None = None
    additional_choices: list[CompletionChoice] | None = None
    raw: dict[str, Any] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class CompletionChoice:
    """CompletionChoice represents one of potentially multiple completions (OpenAI n > 1)."""
    index: int
    message: Message
    stop_reason: StopReason
    native_stop_reason: str


@dataclass(kw_only=True)
class SafetyRating:
    """SafetyRating is a Gemini per-category safety assessment."""
    category: str
    probability: str
    blocked: bool | None = None


@dataclass(kw_only=True)
class SafetySetting:
    """SafetySetting configures Gemini safety thresholds."""
    category: str
    threshold: str


@dataclass(kw_only=True)
class LogProbs:
    """LogProbs contains OpenAI token log probability data."""
    content: list[TokenLogProb] | None = None


@dataclass(kw_only=True)
class TokenLogProb:
    """TokenLogProb is the log probability for a single token."""
    token: str
    logprob: float
    bytes: list[int] | None = None
    top_logprobs: list[TopLogProb] | None = None


@dataclass(kw_only=True)
class TopLogProb:
    """TopLogProb is one of the top-k alternative tokens."""
    token: str
    logprob: float
    bytes: list[int] | None = None


# ────────────────────────────────────────
# source: server.go


@dataclass(kw_only=True)
class ManagedSession:
    """ManagedSession is a session as tracked by llm-bridge-server. This is the server's lightweight session management entity, distinct from [Session] which models rich agent-level state (usage, tasks, context).  Three IDs track a session through its lifecycle:   - BridgeID: server-generated primary key, stable from creation.   - HarnessID: the canonical harness session ID (e.g. CC UUID). Empty until     the harness reports it on first event.   - ClientID: the frontend's correlation key (fe_*). Set at creation,     never changes. Used by the frontend to relate the response back to its     optimistic UI entry."""
    bridge_id: str
    harness_id: str | None = None
    client_id: str | None = None
    display_name: str
    harness: Harness
    instance_id: str | None = None
    state: str
    pid: int | None = None
    agent_id: str | None = None
    spawner_id: str | None = None
    parent_id: str | None = None
    harness_config: dict[str, Any] | None = None  # opaque harness-specific config
    info: SessionInfo | None = None  # latest session info reported by the harness
    folder_name: str | None = None  # user-assigned sidebar folder; empty = unfiled
    created_at: str
    updated_at: str


@dataclass(kw_only=True)
class HarnessInfo:
    """HarnessInfo describes a registered harness type and its capabilities."""
    name: str
    label: str
    emoji: str
    image: str | None = None
    available: bool
    binary: str | None = None
    capabilities: list[str]
    supported_providers: list[str] | None = None


@dataclass(kw_only=True)
class Credential:
    """Credential represents an API credential as exposed by the server. Sensitive fields are masked (api_key_masked, token_masked)."""
    id: str
    provider: str
    label: str
    auth_type: str
    api_key_masked: str | None = None
    token_masked: str | None = None
    priority: int
    enabled: bool
    expires_at: int
    error_count: int | None = None
    last_error: str | None = None


@dataclass(kw_only=True)
class HarnessDefaults:
    """HarnessDefaults stores per-harness configuration defaults."""
    model: str | None = None
    effort: str | None = None
    max_budget: float | None = None
    disabled_tools: list[str] | None = None


@dataclass(kw_only=True)
class BridgePrefs:
    """BridgePrefs stores user preferences for the bridge dashboard."""
    last_harness: str | None = None
    last_instance_id: str | None = None
    last_session: dict[str, str] | None = None
    last_instance: dict[str, str] | None = None
    defaults: dict[str, HarnessDefaults] | None = None


@dataclass(kw_only=True)
class MaterializedMessage:
    """MaterializedMessage is a flattened message returned by the messages API. Assembled from raw events by log-store: stream deltas are concatenated, tool calls are collected, and the final ResultEvent becomes Meta."""
    id: str | None = None  # canonical bridge MessageID
    harness_message_id: str | None = None  # harness-native id, if known
    role: str
    content: str
    thinking: str | None = None
    tools: list[MaterializedTool] | None = None
    meta: ResultEvent | None = None
    events: list[dict[str, Any]] | None = None
    timestamp: str
    done: bool


@dataclass(kw_only=True)
class MaterializedTool:
    """MaterializedTool records a tool invocation within a materialized message."""
    tool_id: str
    tool: str
    input: dict[str, Any] | None = None
    output: str | None = None
    error: bool | None = None


@dataclass(kw_only=True)
class HealthResponse:
    """HealthResponse is the server's health check response."""
    status: str
    harnesses: list[HarnessInfo]
    sessions: SessionCounts


@dataclass(kw_only=True)
class SessionCounts:
    """SessionCounts is a breakdown of active sessions by state."""
    running: int
    idle: int
    completed: int

# ConformanceFeature is a capability that a harness may or may not support.
ConformanceFeature = str


@dataclass(kw_only=True)
class ConformanceTestResult:
    """ConformanceTestResult records the outcome of a single feature test."""
    feature: ConformanceFeature
    passed: bool
    skipped: bool | None = None
    error: str | None = None
    duration: str | None = None


@dataclass(kw_only=True)
class ConformanceHarnessResult:
    """ConformanceHarnessResult records all test results for a single harness."""
    harness: str
    binary: str
    tested_at: str
    results: list[ConformanceTestResult]
    summary: ConformanceSummary


@dataclass(kw_only=True)
class ConformanceSummary:
    """ConformanceSummary counts test outcomes."""
    total: int
    passed: int
    failed: int
    skipped: int


@dataclass(kw_only=True)
class ConformanceMatrix:
    """ConformanceMatrix holds conformance results for all tested harnesses."""
    generated_at: str
    harnesses: list[ConformanceHarnessResult]


@dataclass(kw_only=True)
class CreateSessionRequest:
    """CreateSessionRequest is the request body for POST /sessions."""
    harness: Harness
    instance_id: str | None = None
    display_name: str | None = None
    agent_id: str | None = None
    spawner_id: str | None = None
    auto_start: bool | None = None
    client_id: str | None = None
    harness_config: dict[str, Any] | None = None  # opaque harness-specific config, merged into start params


@dataclass(kw_only=True)
class SendMessageRequest:
    """SendMessageRequest is the request body for POST /sessions/{id}/send.  ClientRequestID is a caller-minted identifier for this turn. The bridge stamps it on every event it emits for the turn so producers can correlate server-side state with their own outbound request. Optional — callers that don't need correlation can leave it empty."""
    message: str
    client_request_id: str | None = None


@dataclass(kw_only=True)
class ForkSessionRequest:
    """ForkSessionRequest is the request body for POST /sessions/{id}/fork."""
    display_name: str | None = None
    client_id: str | None = None


@dataclass(kw_only=True)
class CompactSessionRequest:
    """CompactSessionRequest is the request body for POST /sessions/{id}/compact."""
    summary: str | None = None


@dataclass(kw_only=True)
class ConfigSessionRequest:
    """ConfigSessionRequest is the request body for POST /sessions/{id}/config."""
    model: str | None = None
    effort: str | None = None
    disabled_tools: list[str] | None = None
    max_budget: float | None = None


@dataclass(kw_only=True)
class CreateInstanceRequest:
    """CreateInstanceRequest is the request body for POST /instances."""
    harness_type: str
    name: str
    host: str | None = None
    transport: Transport | None = None
    ssh_user: str | None = None
    ssh_key_path: str | None = None
    ssh_port: int | None = None
    working_dir: str | None = None
    max_concurrent_sessions: int | None = None


@dataclass(kw_only=True)
class BindCredentialRequest:
    """BindCredentialRequest is the request body for POST /instances/{id}/credentials."""
    credential_id: str
    priority: int


@dataclass(kw_only=True)
class RenameSessionRequest:
    """RenameSessionRequest is the request body for POST /sessions/{id}/rename."""
    display_name: str


# ────────────────────────────────────────
# source: session.go


@dataclass(kw_only=True)
class Session:
    """Session represents an agent session across any harness."""
    id: str
    harness: Harness
    state: SessionState
    agent: str | None = None
    orchestrator: str | None = None
    model: str | None = None
    created_at: str
    last_active: str
    ended_at: str | None = None
    context_tokens: int | None = None
    context_limit: int | None = None
    total_usage: TokenUsage
    total_cost: Cost | None = None
    turn_count: int
    config: dict[str, Any] | None = None
    tasks: list[SessionTask] | None = None
    active_request: str | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class SessionTask:
    """SessionTask tracks a task within a session."""
    content: str
    status: str
    active_form: str | None = None


@dataclass(kw_only=True)
class StoredSession:
    """StoredSession represents a session discovered on disk from a harness's native storage (e.g. ~/.claude/projects/ or ~/.codex/sessions/). These are sessions that exist outside the llm-bridge-server's own store."""
    id: str
    harness: Harness
    project: str | None = None  # project directory or context
    prompt: str | None = None  # initial prompt snippet
    created_at: str
    updated_at: str  # file modification time
    path: str  # on-disk path to session file
    turn_count: int | None = None  # approximate number of turns


# ────────────────────────────────────────
# source: session_meta.go


@dataclass(kw_only=True)
class FolderList:
    """FolderList is the ordered list of user-defined folder names for organizing sessions in the sidebar. Folder assignment per session lives on [ManagedSession.FolderName] so it travels with the session row."""
    folder_order: list[str]


@dataclass(kw_only=True)
class CreateFolderRequest:
    """CreateFolderRequest is the body for POST /folders."""
    name: str


@dataclass(kw_only=True)
class RenameFolderRequest:
    """RenameFolderRequest is the body for PUT /folders/{name}."""
    new_name: str


@dataclass(kw_only=True)
class SetSessionFolderRequest:
    """SetSessionFolderRequest is the body for PUT /sessions/{id}/folder. An empty Folder string clears the assignment (un-files the session)."""
    folder: str


# ────────────────────────────────────────
# source: stream.go

# StreamEventType identifies the kind of streaming event.
StreamEventType = str

StreamEventStart: StreamEventType = "stream_start"
StreamEventContentBlockStart: StreamEventType = "content_block_start"
StreamEventContentBlockDelta: StreamEventType = "content_block_delta"
StreamEventContentBlockStop: StreamEventType = "content_block_stop"
StreamEventMessageDelta: StreamEventType = "message_delta"
StreamEventMessageStop: StreamEventType = "message_stop"
StreamEventPing: StreamEventType = "ping"
StreamEventError: StreamEventType = "error"


@dataclass(kw_only=True)
class StreamEvent:
    """StreamEvent is the unified streaming event type. Follows Anthropic's granular model (most expressive) and synthesizes block-level events for providers that don't have them (OpenAI, Gemini)."""
    type: StreamEventType
    start: StreamStart | None = None
    block_start: BlockStart | None = None
    block_delta: BlockDelta | None = None
    block_stop: BlockStop | None = None
    msg_delta: MessageDelta | None = None
    error: StreamError | None = None
    raw: dict[str, Any] | None = None
    extensions: dict[str, dict[str, Any]] | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class StreamStart:
    """StreamStart carries initial message metadata."""
    id: str
    model: str
    provider: Provider
    usage: TokenUsage


@dataclass(kw_only=True)
class BlockStart:
    """BlockStart signals a new content block beginning."""
    index: int
    block: ContentBlock

# DeltaType identifies the kind of streaming delta.
DeltaType = str

DeltaText: DeltaType = "text_delta"
DeltaInputJSON: DeltaType = "input_json_delta"
DeltaThinking: DeltaType = "thinking_delta"
DeltaSignature: DeltaType = "signature_delta"
DeltaAudio: DeltaType = "audio_delta"


@dataclass(kw_only=True)
class BlockDelta:
    """BlockDelta carries incremental content for a block."""
    index: int
    type: DeltaType
    text: str | None = None
    partial_json: str | None = None
    thinking: str | None = None
    signature: str | None = None
    audio_data: str | None = None


@dataclass(kw_only=True)
class BlockStop:
    """BlockStop signals a content block has finished."""
    index: int


@dataclass(kw_only=True)
class MessageDelta:
    """MessageDelta carries end-of-message metadata."""
    stop_reason: StopReason
    native_stop_reason: str | None = None
    stop_sequence: str | None = None
    usage: TokenUsage


@dataclass(kw_only=True)
class StreamError:
    """StreamError represents an error during streaming."""
    type: str
    message: str
    code: str | None = None
    retryable: bool | None = None
    retry_after_ms: int | None = None
    status_code: int | None = None


# ────────────────────────────────────────
# source: tool.go


@dataclass(kw_only=True)
class ToolDef:
    """ToolDef defines a tool the model can call."""
    name: str
    description: str
    input_schema: dict[str, Any]
    strict: bool | None = None
    cache_control: CacheControl | None = None
    _overflow: dict[str, dict[str, Any]] | None = None

# ToolChoiceMode determines how the model selects tools.
ToolChoiceMode = str

ToolChoiceAuto: ToolChoiceMode = "auto"
ToolChoiceAny: ToolChoiceMode = "any"
ToolChoiceNone: ToolChoiceMode = "none"
ToolChoiceRequired: ToolChoiceMode = "required"
ToolChoiceSpecific: ToolChoiceMode = "specific"


@dataclass(kw_only=True)
class ToolChoice:
    """ToolChoice controls model tool selection behavior."""
    mode: ToolChoiceMode
    name: str | None = None
    disable_parallel: bool | None = None


# ────────────────────────────────────────
# source: usage.go


@dataclass(kw_only=True)
class TokenUsage:
    """TokenUsage tracks token consumption across all providers."""
    input_tokens: int
    output_tokens: int
    total_tokens: int
    cache_read_tokens: int | None = None
    cache_write_tokens: int | None = None
    reasoning_tokens: int | None = None
    context_tokens: int | None = None
    context_limit: int | None = None
    _overflow: dict[str, dict[str, Any]] | None = None


@dataclass(kw_only=True)
class Cost:
    """Cost tracks monetary cost of a request."""
    total_usd: float
    input_usd: float | None = None
    output_usd: float | None = None
    is_byok: bool | None = None
    upstream_cost: float | None = None


# ────────────────────────────────────────
# source: validate.go


@dataclass(kw_only=True)
class ValidationError:
    """ValidationError contains one or more validation failures."""
    failures: list[ValidationFailure]


@dataclass(kw_only=True)
class ValidationFailure:
    """ValidationFailure describes a single validation issue."""
    path: str
    code: str
    message: str

# Validation error codes — conversation/response.
ErrEmptyField = "empty_field"
ErrInvalidRole = "invalid_role"
ErrInvalidBlockType = "invalid_block_type"
ErrMultipleBlocksSet = "multiple_blocks_set"
ErrNoBlockSet = "no_block_set"
ErrMissingToolID = "missing_tool_id"
ErrMissingToolName = "missing_tool_name"
ErrOrphanedToolResult = "orphaned_tool_result"
ErrAlternationViolation = "alternation_violation"
ErrMissingModel = "missing_model"
ErrMissingProvider = "missing_provider"
ErrInvalidStopReason = "invalid_stop_reason"
ErrThinkingNoSignature = "thinking_no_signature"
ErrOpaqueDataModified = "opaque_data_modified"

# Validation error codes — event/session.
ErrMissingSessionID = "missing_session_id"
ErrMissingHarness = "missing_harness"
ErrInvalidEventType = "invalid_event_type"
ErrNoEventPayload = "no_event_payload"
ErrMultiplePayloads = "multiple_payloads"
ErrInvalidSessionState = "invalid_session_state"
ErrMissingTimestamp = "missing_timestamp"
